In [1]:
import json
import pandas as pd
import geopandas as gpd

gdf_2010 = gpd.read_file('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/landvalue_2010_new.geojson')
#gdf_2010 = gdf_2010.rename(columns={'roll_totalvalue': 'roll_totalvalue_2010'})
#gdf_2010.set_index('ain',inplace=True)
gdf_2010

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,location_1,OBJECTID_left,neighborhood,index_right,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,227767,0,2002,953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,...,"{'latitude': '34.05402081', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28692 34.05402)
1,5076004042,90006,34.05416636,-118.28739291,2010,58918,1050,2010,"940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
2,5076004067,90006,34.05416636,-118.28739291,2010,82485,1470,2010,"940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
3,5076004028,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
4,5076004030,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41149,5443034007,90039-3714,34.09879045,-118.25012427,2010,47196,1344,1985,2010 SUNFLOWER AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09879045', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25012 34.09879)
41150,5443034040,90039-3708,34.09793157,-118.24867157,2010,44712,897,1980,1903 ROSEBUD AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09793157', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24867 34.09793)
41151,5443030020,90039-3715,34.09685223,-118.24962420,2010,50203,2818,2007,1909 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09685223', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24962 34.09685)
41152,5443035014,90039-3707,34.09866725,-118.24913765,2010,549257,12377,1987,2000 RIVERSIDE DR LOS ANGELES CA 90039,Commercial,...,"{'latitude': '34.09866725', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24914 34.09867)
41153,5443030015,90039-3715,34.09689235,-118.24994122,2010,140148,1115,1996,1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09689235', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24994 34.09689)