**Land value notebook**

In [1]:
import requests
import json
import pandas as pd
import geopandas as gpd

requestString = 'https://data.lacounty.gov/resource/4bch-gpkr.json?City=LOS ANGELES CA&$limit=1000000'
r = requests.get(requestString)
d = json.loads(r.text)
df_2010 = pd.DataFrame(d)
df_2010

,usecodedescchar1,roll_homeownersexemp,situsunit,recordingdate,effectiveyearbuilt,istaxableparcel,roll_totlandimp,roll_perspropexemp,parcelboundarydescription,roll_landbaseyear,...,roll_totalexemption,totbuildingdatalines,location_1,bathrooms,sqftmain,situsdirection,roll_realestateexemp,center_lat,situszip,yearbuilt
0,Commercial,0,,19980924,0,Y,455441,0,TRACT NO 1OO74 LOT 23,1999,...,0,0,"{'latitude': '34.14427971', 'needs_recoding': ...",0,0,,0,34.14427971,91604-2602,0
1,Commercial,0,,19960301,1948,Y,559830,0,TRACT # 6834 LOT 1,1996,...,0,1,"{'latitude': '34.05496569', 'needs_recoding': ...",0,2400,W,0,34.05496569,90035-3333,1948
2,Commercial,0,,20000901,0,Y,303510,0,TR=3365 LOT 16,2001,...,0,0,"{'latitude': '33.99757582', 'needs_recoding': ...",0,0,W,0,33.99757582,90043-4820,0
3,Commercial,0,,20091013,1962,Y,800000,0,TRACT # 6170 LOT 1557,2010,...,0,1,"{'latitude': '34.16665133', 'needs_recoding': ...",0,2800,,0,34.16665133,91364-1415,1955
4,Residential,7000,,19851216,1956,Y,212877,0,TRACT # 20652 LOT 81,1986,...,7000,1,"{'latitude': '34.18918432', 'needs_recoding': ...",2,1584,,0,34.18918432,91335-5725,1956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
778444,Residential,0,,20050811,1952,Y,276700,0,TRACT # 16754 LOT 84,2003,...,0,1,"{'latitude': '34.19274212', 'needs_recoding': ...",2,1299,,0,34.19274212,91335-4908,1951
778445,Residential,0,,20070314,1952,Y,295900,0,TRACT # 16754 LOT 87,2007,...,0,1,"{'latitude': '34.19242245', 'needs_recoding': ...",2,1125,,0,34.19242245,91335-4918,1951
778446,Residential,0,,20070402,1951,Y,62825,0,TRACT # 16754 LOT 85,1975,...,0,1,"{'latitude': '34.19275036', 'needs_recoding': ...",2,1119,,0,34.19275036,91335-4918,1951
778447,Residential,7000,,20050302,1959,Y,274400,0,TRACT # 16754 LOT 86,2005,...,7000,1,"{'latitude': '34.1925865', 'needs_recoding': F...",2,1372,,0,34.19258650,91335-4918,1951
778448,Residential,7000,,20060714,1962,Y,405000,0,TRACT # 16754 LOT 81,2007,...,7000,1,"{'latitude': '34.19221974', 'needs_recoding': ...",3,1539,,0,34.19221974,91335-4908,1951

In [2]:
df_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 778449 entries, 0 to 778448
Data columns (total 51 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   usecodedescchar1           778435 non-null  object
 1   roll_homeownersexemp       778449 non-null  object
 2   situsunit                  778449 non-null  object
 3   recordingdate              778449 non-null  object
 4   effectiveyearbuilt         778449 non-null  object
 5   istaxableparcel            778449 non-null  object
 6   roll_totlandimp            778449 non-null  object
 7   roll_perspropexemp         778449 non-null  object
 8   parcelboundarydescription  778449 non-null  object
 9   roll_landbaseyear          778449 non-null  object
 10  situscity                  778449 non-null  object
 11  roll_impbaseyear           778449 non-null  object
 12  usetype                    778435 non-null  object
 13  cluster                    778449 non-null  object
 14  adminregion                778449 non-null  object
 15  usecodedescchar3           778435 non-null  object
 16  roll_fixtureexemp          778449 non-null  object
 17  propertylocation           778449 non-null  object
 18  nettaxablevalue            778449 non-null  object
 19  taxratearea                778449 non-null  object
 20  rowid                      778449 non-null  object
 21  roll_landvalue             778449 non-null  object
 22  units                      778449 non-null  object
 23  taxratearea_city           778449 non-null  object
 24  situsfraction              778449 non-null  object
 25  roll_impvalue              778449 non-null  object
 26  usecode                    778449 non-null  object
 27  situsstreet                778449 non-null  object
 28  situszip5                  778442 non-null  object
 29  parcelclassification       778449 non-null  object
 30  assessorid                 778449 non-null  object
 31  roll_perspropvalue         778449 non-null  object
 32  bedrooms                   778449 non-null  object
 33  usecodedescchar2           778435 non-null  object
 34  roll_totalvalue            778449 non-null  object
 35  rollyear                   778449 non-null  object
 36  ain                        778449 non-null  object
 37  situshouseno               778449 non-null  object
 38  roll_fixturevalue          778449 non-null  object
 39  usecodedescchar4           778435 non-null  object
 40  center_lon                 778389 non-null  object
 41  roll_totalexemption        778449 non-null  object
 42  totbuildingdatalines       778449 non-null  object
 43  location_1                 778389 non-null  object
 44  bathrooms                  778449 non-null  object
 45  sqftmain                   778449 non-null  object
 46  situsdirection             778449 non-null  object
 47  roll_realestateexemp       778449 non-null  object
 48  center_lat                 778389 non-null  object
 49  situszip                   778449 non-null  object
 50  yearbuilt                  778449 non-null  object
dtypes: object(51)
memory usage: 302.9+ MB

In [3]:
#keep the desired columns
columns = ['ain','situszip','center_lat','center_lon','rollyear','roll_totalvalue','location_1','propertylocation','usecodedescchar1','effectiveyearbuilt','parcelboundarydescription','roll_landbaseyear',' situscity']
df_2010_n = pd.DataFrame(df_2010, columns=columns)
df_2010_n

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity
0,2368002003,91604-2602,34.14427971,-118.39342202,2010,455441,"{'latitude': '34.14427971', 'needs_recoding': ...",12021 VENTURA PL LOS ANGELES CA 91604,Commercial,0,TRACT NO 1OO74 LOT 23,1999,NaN
1,4305007001,90035-3333,34.05496569,-118.38783830,2010,559830,"{'latitude': '34.05496569', 'needs_recoding': ...",8980 W PICO BLVD LOS ANGELES CA 90035,Commercial,1948,TRACT # 6834 LOT 1,1996,NaN
2,5013019033,90043-4820,33.99757582,-118.33022729,2010,303510,"{'latitude': '33.99757582', 'needs_recoding': ...",3322 W 50TH ST LOS ANGELES CA 90043,Commercial,0,TR=3365 LOT 16,2001,NaN
3,2040032015,91364-1415,34.16665133,-118.62008217,2010,800000,"{'latitude': '34.16665133', 'needs_recoding': ...",22644 VENTURA BLVD LOS ANGELES CA 91364,Commercial,1962,TRACT # 6170 LOT 1557,2010,NaN
4,2132011025,91335-5725,34.18918432,-118.56057599,2010,212877,"{'latitude': '34.18918432', 'needs_recoding': ...",19615 HAMLIN ST LOS ANGELES CA 91335,Residential,1956,TRACT # 20652 LOT 81,1986,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
778444,2132007010,91335-4908,34.19274212,-118.55846445,2010,276700,"{'latitude': '34.19274212', 'needs_recoding': ...",6724 BELMAR AVE LOS ANGELES CA 91335,Residential,1952,TRACT # 16754 LOT 84,2003,NaN
778445,2132007013,91335-4918,34.19242245,-118.55813209,2010,295900,"{'latitude': '34.19242245', 'needs_recoding': ...",6707 SHIRLEY AVE LOS ANGELES CA 91335,Residential,1952,TRACT # 16754 LOT 87,2007,NaN
778446,2132007011,91335-4918,34.19275036,-118.55813397,2010,62825,"{'latitude': '34.19275036', 'needs_recoding': ...",6719 SHIRLEY AVE LOS ANGELES CA 91335,Residential,1951,TRACT # 16754 LOT 85,1975,NaN
778447,2132007012,91335-4918,34.19258650,-118.55813240,2010,274400,"{'latitude': '34.1925865', 'needs_recoding': F...",6713 SHIRLEY AVE LOS ANGELES CA 91335,Residential,1959,TRACT # 16754 LOT 86,2005,NaN
778448,2132007007,91335-4908,34.19221974,-118.55846464,2010,405000,"{'latitude': '34.19221974', 'needs_recoding': ...",6706 BELMAR AVE LOS ANGELES CA 91335,Residential,1962,TRACT # 16754 LOT 81,2007,NaN

In [4]:
gdf_2010 = gpd.GeoDataFrame(
    df_2010_n, geometry=gpd.points_from_xy(df_2010_n.center_lon, df_2010_n.center_lat, 
                                          crs='EPSG:4326'))
gdf_2010.head()

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry
0,2368002003,91604-2602,34.14427971,-118.39342202,2010,455441,"{'latitude': '34.14427971', 'needs_recoding': ...",12021 VENTURA PL LOS ANGELES CA 91604,Commercial,0,TRACT NO 1OO74 LOT 23,1999,NaN,POINT (-118.39342 34.14428)
1,4305007001,90035-3333,34.05496569,-118.38783830,2010,559830,"{'latitude': '34.05496569', 'needs_recoding': ...",8980 W PICO BLVD LOS ANGELES CA 90035,Commercial,1948,TRACT # 6834 LOT 1,1996,NaN,POINT (-118.38784 34.05497)
2,5013019033,90043-4820,33.99757582,-118.33022729,2010,303510,"{'latitude': '33.99757582', 'needs_recoding': ...",3322 W 50TH ST LOS ANGELES CA 90043,Commercial,0,TR=3365 LOT 16,2001,NaN,POINT (-118.33023 33.99758)
3,2040032015,91364-1415,34.16665133,-118.62008217,2010,800000,"{'latitude': '34.16665133', 'needs_recoding': ...",22644 VENTURA BLVD LOS ANGELES CA 91364,Commercial,1962,TRACT # 6170 LOT 1557,2010,NaN,POINT (-118.62008 34.16665)
4,2132011025,91335-5725,34.18918432,-118.56057599,2010,212877,"{'latitude': '34.18918432', 'needs_recoding': ...",19615 HAMLIN ST LOS ANGELES CA 91335,Residential,1956,TRACT # 20652 LOT 81,1986,NaN,POINT (-118.56058 34.18918)

In [1]:
import requests
import json
import pandas as pd
import geopandas as gpd

#zipcodes of ktown
ziplist_ktown = ['90005','90006','90010']

df_ktown = pd.DataFrame()

for x in ziplist_ktown: 
    r = requests.get('https://data.lacounty.gov/resource/9trm-uz8i.json?situszip5={}&$limit=1000000'.format(x))
    d = pd.DataFrame(json.loads(r.text))
    df_ktown = pd.concat([df_ktown, d], axis=0).reset_index(drop=True)
    
df_ktown

,situszip,taxratearea_city,ain,rollyear,taxratearea,assessorid,propertylocation,usetype,usecode,usecodedescchar1,...,situszip5,rowid,center_lat,center_lon,location_1,situsdirection,situsunit,usecodedescchar3,parcelclassification,situsfraction
0,90005-1170,LOS ANGELES,5077016026,2019,06657,5077-016-026,731 MAGNOLIA AVE LOS ANGELES CA 90005,VAC,010V,Residential,...,90005,20195077016026,34.059053349999999,-118.28636661,"{'latitude': '34.05905335', 'longitude': '-118...",NaN,NaN,NaN,NaN,NaN
1,90005-1225,LOS ANGELES,5077021004,2019,00067,5077-021-004,2730 W 8TH ST LOS ANGELES CA 90005,VAC,010V,Residential,...,90005,20195077021004,34.057460720000002,-118.28509803,"{'latitude': '34.05746072', 'longitude': '-118...",W,NaN,NaN,NaN,NaN
2,90005-2333,LOS ANGELES,5094003013,2019,06657,5094-003-013,715 IROLO ST LOS ANGELES CA 90005,SFR,0100,Residential,...,90005,20195094003013,34.059242810000001,-118.30123077,"{'latitude': '34.05924281', 'longitude': '-118...",NaN,NaN,NaN,NaN,NaN
3,90005-3268,LOS ANGELES,5504017027,2019,00067,5504-017-027,"601 S VAN NESS AVE, 6 LOS ANGELES CA 90005",CND,010C,Residential,...,90005,20195504017027,34.062895150000003,-118.31574368,"{'latitude': '34.06289515', 'longitude': '-118...",S,6,NaN,NaN,NaN
4,90005-3841,LOS ANGELES,5505007005,2019,00067,5505-007-005,634 S RIMPAU BLVD LOS ANGELES CA 90005,SFR,0101,Residential,...,90005,20195505007005,34.063013419999997,-118.33121251,"{'latitude': '34.06301342', 'longitude': '-118...",S,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135973,90010-3814,LOS ANGELES,5507017140,2021,00067,5507-017-140,"4801 WILSHIRE BLVD, NO 320 LOS ANGELES CA 90010",C/I,170C,Commercial,...,90010,20215507017140,34.062373209999997,-118.33506523,"{'latitude': '34.06237321', 'longitude': '-118...",NaN,NO 320,NaN,NaN,NaN
135974,90010-2895,LOS ANGELES,5503030180,2021,06657,5503-030-180,"3785 WILSHIRE BLVD, NO 2106 LOS ANGELES CA ...",CND,01HC,Residential,...,90010,20215503030180,34.062775170000002,-118.30871996,"{'latitude': '34.06277517', 'longitude': '-118...",NaN,NO 2106,High Rise 5 Stories or More,NaN,NaN
135975,90010-2892,LOS ANGELES,5503030138,2021,06657,5503-030-138,"3785 WILSHIRE BLVD, NO 1712 LOS ANGELES CA ...",CND,01HC,Residential,...,90010,20215503030138,34.062775170000002,-118.30871996,"{'latitude': '34.06277517', 'longitude': '-118...",NaN,NO 1712,High Rise 5 Stories or More,NaN,NaN
135976,90010,LOS ANGELES,5503030048,2021,06657,5503-030-048,"3785 WILSHIRE BLVD, NO 806 LOS ANGELES CA ...",CND,01HC,Residential,...,90010,20215503030048,34.062775170000002,-118.30871996,"{'latitude': '34.06277517', 'longitude': '-118...",NaN,NO 806,High Rise 5 Stories or More,NaN,NaN
135977,90010,LOS ANGELES,6061012032,2021,00212,6061-012-032,702 W 104TH PL LOS ANGELES CA 90010,R-I,0400,Residential,...,90010,20216061012032,33.94133377,-118.28726196,"{'latitude': '33.94133377', 'longitude': '-118...",W,NaN,4 Stories or Less,NaN,NaN

In [5]:
#import neighborhood boundary data
nb= gpd.read_file('/Users/jinglanlin/Desktop/School/01 UCLA/04 Spring 2022/UP 229 DS/Github/UDS-Project--Full-Team-/Data/LA_Times_Neighborhood_Boundaries (1)-Copy1.geojson')
nb.head()

,OBJECTID,name,geometry
0,1,Adams-Normandie,"POLYGON ((-118.30069 34.03731, -118.30388 34.0..."
1,2,Arleta,"POLYGON ((-118.44255 34.26412, -118.44240 34.2..."
2,3,Arlington Heights,"POLYGON ((-118.31862 34.05306, -118.31673 34.0..."
3,4,Atwater Village,"MULTIPOLYGON (((-118.27886 34.15321, -118.2788..."
4,5,Baldwin Hills/Crenshaw,"POLYGON ((-118.36102 34.02532, -118.36026 34.0..."

In [6]:
#join neighborhood boundary with land value data
gdf_2010_sjoin = gpd.sjoin(gdf_2010,nb.to_crs('EPSG:4326'),how="left", predicate='intersects')
gdf_2010_sjoin.head()

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,index_right,OBJECTID,name
0,2368002003,91604-2602,34.14427971,-118.39342202,2010,455441,"{'latitude': '34.14427971', 'needs_recoding': ...",12021 VENTURA PL LOS ANGELES CA 91604,Commercial,0,TRACT NO 1OO74 LOT 23,1999,NaN,POINT (-118.39342 34.14428),86.0,87.0,Studio City
1,4305007001,90035-3333,34.05496569,-118.38783830,2010,559830,"{'latitude': '34.05496569', 'needs_recoding': ...",8980 W PICO BLVD LOS ANGELES CA 90035,Commercial,1948,TRACT # 6834 LOT 1,1996,NaN,POINT (-118.38784 34.05497),72.0,73.0,Pico-Robertson
2,5013019033,90043-4820,33.99757582,-118.33022729,2010,303510,"{'latitude': '33.99757582', 'needs_recoding': ...",3322 W 50TH ST LOS ANGELES CA 90043,Commercial,0,TR=3365 LOT 16,2001,NaN,POINT (-118.33023 33.99758),50.0,51.0,Hyde Park
3,2040032015,91364-1415,34.16665133,-118.62008217,2010,800000,"{'latitude': '34.16665133', 'needs_recoding': ...",22644 VENTURA BLVD LOS ANGELES CA 91364,Commercial,1962,TRACT # 6170 LOT 1557,2010,NaN,POINT (-118.62008 34.16665),112.0,113.0,Woodland Hills
4,2132011025,91335-5725,34.18918432,-118.56057599,2010,212877,"{'latitude': '34.18918432', 'needs_recoding': ...",19615 HAMLIN ST LOS ANGELES CA 91335,Residential,1956,TRACT # 20652 LOT 81,1986,NaN,POINT (-118.56058 34.18918),78.0,79.0,Reseda

In [7]:
#keep data with the following neighborhood: Koreatown, Westlake, Silver Lake, Echo Park, Downtown, Pico Union
Westlake = gdf_2010_sjoin.loc[gdf_2010_sjoin['name'] == 'Westlake']
Westlake = Westlake.drop(['index_right'], axis=1)
Westlake

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
435206,5076004007,90006-5707,34.05402081,-118.28692121,2010,228886,"{'latitude': '34.05402081', 'needs_recoding': ...",953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,1960,CLARK AND BRYAN'S WESTMORELAND TRACT N 50 FT O...,2002,NaN,POINT (-118.28692 34.05402),107.0,Westlake
435207,5076004042,90006,34.05416636,-118.28739291,2010,316201,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 204 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
435208,5076004067,90006,34.05416636,-118.28739291,2010,442683,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 502 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
435209,5076004028,90006,34.05416636,-118.28739291,2010,367397,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 110 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
435210,5076004030,90006,34.05416636,-118.28739291,2010,433648,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 102 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558325,5501022006,90020-1110,34.06752533,-118.28491804,2010,98026,"{'latitude': '34.06752533', 'needs_recoding': ...",3116 GENEVA ST LOS ANGELES CA 90020,Residential,1929,GENEVA TRACT W 49.80 FT OF LOT 5,1980,NaN,POINT (-118.28492 34.06753),107.0,Westlake
558330,5501021003,90020-1101,34.06844902,-118.28604930,2010,460374,"{'latitude': '34.06844902', 'needs_recoding': ...",315 S COMMONWEALTH AVE LOS ANGELES CA 90020,Residential,1939,TRACT # 722 LOT 11,2010,NaN,POINT (-118.28605 34.06845),107.0,Westlake
558331,5501022040,90020-1171,34.06705534,-118.28525940,2010,237000,"{'latitude': '34.06705534', 'needs_recoding': ...","370 S COMMONWEALTH AVE, NO 9 LOS ANGELES CA ...",Residential,1982,*TR=37790 CONDOMINIUM*UNIT 9,2006,NaN,POINT (-118.28526 34.06706),107.0,Westlake
558333,5501021044,90020-1319,34.06793228,-118.28643496,2010,323433,"{'latitude': '34.06793228', 'needs_recoding': ...","332 S VIRGIL AVE, 601 LOS ANGELES CA 90020",Residential,2008,TR=61449 LOT 1 CONDO UNIT 12 (AIRSPACE AND 1/1...,2004,NaN,POINT (-118.28643 34.06793),107.0,Westlake
558336,5501022037,90020-1171,34.06705534,-118.28525940,2010,261000,"{'latitude': '34.06705534', 'needs_recoding': ...","370 S COMMONWEALTH AVE, NO 6 LOS ANGELES CA ...",Residential,1982,*TR=37790 CONDOMINIUM*UNIT 6,2010,NaN,POINT (-118.28526 34.06706),107.0,Westlake

In [8]:
Koreatown = gdf_2010_sjoin.loc[gdf_2010_sjoin['name'] == 'Koreatown']
Koreatown = Koreatown.drop(['index_right'], axis=1)
Koreatown

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
433967,5077017002,90005-1488,34.05945444,-118.28971120,2010,446440,"{'latitude': '34.05945444', 'needs_recoding': ...",3014 W 7TH ST LOS ANGELES CA 90005,Commercial,1931,FULMER TRACT LOTS 26 AND LOT 27,1982,NaN,POINT (-118.28971 34.05945),53.0,Koreatown
435079,5076001008,90006-2863,34.05378701,-118.29072004,2010,1268472,"{'latitude': '34.05378701', 'needs_recoding': ...",957 MENLO AVE LOS ANGELES CA 90006,Residential,1964,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 178 A...,2009,NaN,POINT (-118.29072 34.05379),53.0,Koreatown
435082,5076001006,90006-2862,34.05415833,-118.29072117,2010,1564320,"{'latitude': '34.05415833', 'needs_recoding': ...",947 MENLO AVE LOS ANGELES CA 90006,Residential,1962,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 176,2009,NaN,POINT (-118.29072 34.05416),53.0,Koreatown
435085,5076001007,90006-2815,34.05399345,-118.29072071,2010,331924,"{'latitude': '34.05399345', 'needs_recoding': ...",951 MENLO AVE LOS ANGELES CA 90006,Residential,1974,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 177,1982,NaN,POINT (-118.29072 34.05399),53.0,Koreatown
435090,5076001004,90006-2803,34.05445998,-118.29072182,2010,441759,"{'latitude': '34.05445998', 'needs_recoding': ...",939 MENLO AVE LOS ANGELES CA 90006,Residential,1924,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 174 A...,2002,NaN,POINT (-118.29072 34.05446),53.0,Koreatown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569326,5518028018,90004-5785,34.07184366,-118.29380183,2010,95494,"{'latitude': '34.07184366', 'needs_recoding': ...",130 S BERENDO ST LOS ANGELES CA 90004,Residential,1922,AMBASSADOR HEIGHTS LOT 34,1975,NaN,POINT (-118.29380 34.07184),53.0,Koreatown
569327,5518032903,90004,34.07347937,-118.29206426,2010,0,"{'latitude': '34.07347937', 'needs_recoding': ...",121 N VERMONT AVE LOS ANGELES CA 90004,Commercial,1983,"LAND DESC AS PAR 4 IN DOC 513081,020305 POR OF...",2000,NaN,POINT (-118.29206 34.07348),53.0,Koreatown
569329,5518033001,90004-4817,34.07583322,-118.29207178,2010,700409,"{'latitude': '34.07583322', 'needs_recoding': ...",245 N VERMONT AVE LOS ANGELES CA 90004,Commercial,1926,TRACT # 6535 LOT 1,1988,NaN,POINT (-118.29207 34.07583),53.0,Koreatown
569330,5518033020,90004-4817,34.07481378,-118.29206852,2010,226550,"{'latitude': '34.07481378', 'needs_recoding': ...",207 N VERMONT AVE LOS ANGELES CA 90004,Commercial,1935,LOT COM N 0¢05'45'' W 63 FT FROM NW COR OF COU...,1975,NaN,POINT (-118.29207 34.07481),53.0,Koreatown
569331,5518031017,90004-5862,34.07190204,-118.29254813,2010,455434,"{'latitude': '34.07190204', 'needs_recoding': ...",124 S NEW HAMPSHIRE AVE LOS ANGELES CA 90004,Residential,1924,TRACT # 3611 LOT 37,1995,NaN,POINT (-118.29255 34.07190),53.0,Koreatown

In [9]:
Pico_Union = gdf_2010_sjoin.loc[gdf_2010_sjoin['name'] == 'Pico-Union']
Pico_Union = Pico_Union.drop(['index_right'], axis=1)
Pico_Union

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
417169,5056008022,90006-4802,34.04698958,-118.28478311,2010,359591,"{'latitude': '34.04698958', 'needs_recoding': ...",2214 W PICO BLVD LOS ANGELES CA 90006,Commercial,1987,TR=827 EX OF ST LOT A,1997,NaN,POINT (-118.28478 34.04699),74.0,Pico-Union
421548,5056004013,90006-4768,34.04653073,-118.28743938,2010,700900,"{'latitude': '34.04653073', 'needs_recoding': ...","2229 W 14TH ST, APT 0005 LOS ANGELES CA 90006",Residential,1964,SHERMAN TRACT LOT 18 BLK A,2010,NaN,POINT (-118.28744 34.04653),74.0,Pico-Union
421549,5056001016,90006-4603,34.04532516,-118.29077190,2010,28640,"{'latitude': '34.04532516', 'needs_recoding': ...",1431 MENLO AVE LOS ANGELES CA 90006,Residential,1916,VERMONT AVE TRACT LOT 17 BLK 1,1975,NaN,POINT (-118.29077 34.04533),74.0,Pico-Union
421551,5056001015,90006-4603,34.04546295,-118.29077240,2010,453000,"{'latitude': '34.04546295', 'needs_recoding': ...",1425 MENLO AVE LOS ANGELES CA 90006,Residential,1905,VERMONT AVE TRACT LOT 16 BLK 1,2006,NaN,POINT (-118.29077 34.04546),74.0,Pico-Union
421553,5056001004,90006-4502,34.04695895,-118.29132673,2010,1076562,"{'latitude': '34.04695895', 'needs_recoding': ...",1300 S VERMONT AVE LOS ANGELES CA 90006,Commercial,1950,VERMONT AVE TRACT EX OF ST LOT 5 AND EX OF STS...,1988,NaN,POINT (-118.29133 34.04696),74.0,Pico-Union
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467297,5137032032,90015-2022,34.04504895,-118.27623945,2010,162495,"{'latitude': '34.04504895', 'needs_recoding': ...","1236 S UNION AVE, 5 LOS ANGELES CA 90015",Residential,1988,TR=43990 LOT 1 CONDOMINIUM UNIT 5,1993,NaN,POINT (-118.27624 34.04505),74.0,Pico-Union
467298,5137032014,90015-2019,34.04469916,-118.27546600,2010,351483,"{'latitude': '34.04469916', 'needs_recoding': ...",1516 W 12TH PL LOS ANGELES CA 90015,Residential,1901,CITY CENTRE TRACT LOT 1 BLK 7,2006,NaN,POINT (-118.27547 34.04470),74.0,Pico-Union
467299,5137033030,90015-2409,34.04522940,-118.27749962,2010,929175,"{'latitude': '34.0452294', 'needs_recoding': F...",1619 W PICO BLVD LOS ANGELES CA 90015,Commercial,2005,WILLIAMSON TRACT LOTS 36 AND 37 BLK 7,2005,NaN,POINT (-118.27750 34.04523),74.0,Pico-Union
467300,5137032031,90015-2022,34.04504895,-118.27623945,2010,162297,"{'latitude': '34.04504895', 'needs_recoding': ...","1236 S UNION AVE, 4 LOS ANGELES CA 90015",Residential,1988,TR=43990 LOT 1 CONDOMINIUM UNIT 4,1989,NaN,POINT (-118.27624 34.04505),74.0,Pico-Union
467301,5137034003,90006-4175,34.04649126,-118.27985842,2010,175653,"{'latitude': '34.04649126', 'needs_recoding': ...",1242 S BONNIE BRAE ST LOS ANGELES CA 90006,Residential,1910,BONNIE BRAE PLACE LOT 6,1995,NaN,POINT (-118.27986 34.04649),74.0,Pico-Union

In [10]:
Downtown = gdf_2010_sjoin.loc[gdf_2010_sjoin['name'] == 'Downtown']
Downtown = Downtown.drop(['index_right'], axis=1)
Downtown

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
461891,5126009015,90015-3722,34.03419540,-118.27103168,2010,758259,"{'latitude': '34.0341954', 'needs_recoding': F...",501 E WASHINGTON BLVD LOS ANGELES CA 90015,Commercial,0,WRIGHT TRACT SW 38 FT EX OF ST OF LOT 25 AND E...,1990,NaN,POINT (-118.27103 34.03420),24.0,Downtown
461894,5126001015,90015-3417,34.03642342,-118.27290533,2010,1072358,"{'latitude': '34.03642342', 'needs_recoding': ...",657 W 18TH ST LOS ANGELES CA 90015,Institutional,1923,PORTION OF BELL'S ADDITION NW 105 FT OF NE 120...,1983,NaN,POINT (-118.27291 34.03642),24.0,Downtown
461899,5126009900,90015,34.03520207,-118.27103336,2010,0,"{'latitude': '34.03520207', 'needs_recoding': ...",1816 S FIGUEROA ST LOS ANGELES CA 90015,Miscellaneous,0,"WRIGHT TRACT LOTS 7,8 AND LOT 9",1975,NaN,POINT (-118.27103 34.03520),24.0,Downtown
461901,5126009014,90015-3423,34.03435722,-118.27092893,2010,309003,"{'latitude': '34.03435722', 'needs_recoding': ...",1841 S FLOWER ST LOS ANGELES CA 90015,Industrial,0,WRIGHT TRACT EX OF ST LOT 24 AND NE 12 FT EX O...,2002,NaN,POINT (-118.27093 34.03436),24.0,Downtown
461904,5126002002,90015,34.03528336,-118.27308314,2010,745960,"{'latitude': '34.03528336', 'needs_recoding': ...",631 E WASHINGTON BLVD LOS ANGELES CA 90015,Commercial,1972,ROBERTSON'S SUB OF LOTS 3 AND 4 BLK 3 BELLS AD...,1980,NaN,POINT (-118.27308 34.03528),24.0,Downtown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521034,5409024165,90012,34.05720539,-118.23537796,2010,184538,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 542 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 542 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
521039,5409024160,90012,34.05720539,-118.23537796,2010,184538,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 537 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 537 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
521046,5409024163,90012,34.05720539,-118.23537796,2010,178960,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 540 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 540 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
521050,5409024161,90012,34.05720539,-118.23537796,2010,184538,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 538 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 538 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
521058,5409024162,90012,34.05720539,-118.23537796,2010,273089,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 539 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 539 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown

In [11]:
Silver_Lake = gdf_2010_sjoin.loc[gdf_2010_sjoin['name'] == 'Silver Lake']
Silver_Lake = Silver_Lake.drop(['index_right'], axis=1)
Silver_Lake

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
516591,5401006042,90026-3575,34.08205622,-118.28161803,2010,221788,"{'latitude': '34.08205622', 'needs_recoding': ...","716 MALTMAN AVE, NO 11 LOS ANGELES CA 90026",Residential,1990,TR=47833 LOT 1 CONDO UNIT 11,2001,NaN,POINT (-118.28162 34.08206),85.0,Silver Lake
516592,5401001007,90026-3548,34.08174819,-118.28393710,2010,558672,"{'latitude': '34.08174819', 'needs_recoding': ...",637 IMOGEN AVE LOS ANGELES CA 90026,Residential,1928,WEST END OCEAN VIEW TRACT LOT 6,2009,NaN,POINT (-118.28394 34.08175),85.0,Silver Lake
516593,5401005021,90026-3626,34.08070690,-118.28190978,2010,81822,"{'latitude': '34.0807069', 'needs_recoding': F...",631 TULAROSA DR LOS ANGELES CA 90026,Residential,1925,WEST END OCEAN VIEW TRACT LOT 76,1975,NaN,POINT (-118.28191 34.08071),85.0,Silver Lake
516594,5401004021,90026-3518,34.08128858,-118.28288564,2010,65674,"{'latitude': '34.08128858', 'needs_recoding': ...",637 MALTMAN AVE LOS ANGELES CA 90026,Residential,1939,WEST END OCEAN VIEW TRACT LOT 31,1975,NaN,POINT (-118.28289 34.08129),85.0,Silver Lake
516595,5401006002,90026-3521,34.08284693,-118.28111914,2010,746000,"{'latitude': '34.08284693', 'needs_recoding': ...",748 MALTMAN AVE LOS ANGELES CA 90026,Residential,1922,WEST END OCEAN VIEW TRACT LOT 48,2009,NaN,POINT (-118.28112 34.08285),85.0,Silver Lake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535146,5440031025,90039-4002,34.10012836,-118.25236922,2010,641000,"{'latitude': '34.10012836', 'needs_recoding': ...",2559 CORRALITAS DR LOS ANGELES CA 90039,Residential,1929,TRACT NO 4038 LOT 30,2006,NaN,POINT (-118.25237 34.10013),85.0,Silver Lake
535147,5440028009,90039-4052,34.09932685,-118.25340760,2010,480945,"{'latitude': '34.09932685', 'needs_recoding': ...",2592 CORRALITAS DR LOS ANGELES CA 90039,Residential,1991,"LAND DES IN DOC NO 91, 75-6-11 TRACT NO 4038 L...",2001,NaN,POINT (-118.25341 34.09933),85.0,Silver Lake
535148,5440029022,90039-4003,34.10057287,-118.25223323,2010,272234,"{'latitude': '34.10057287', 'needs_recoding': ...",2552 CORRALITAS DR LOS ANGELES CA 90039,Residential,1983,TRACT NO 4038 LOT 52,1987,NaN,POINT (-118.25223 34.10057),85.0,Silver Lake
535149,5440026016,90039-4010,34.10136602,-118.25299794,2010,770000,"{'latitude': '34.10136602', 'needs_recoding': ...",2448 RIVERSIDE PL LOS ANGELES CA 90039,Residential,1960,TRACT # 6688 LOT 11,2010,NaN,POINT (-118.25300 34.10137),85.0,Silver Lake
535150,5440031032,90039-4004,34.09920993,-118.25306676,2010,359062,"{'latitude': '34.09920993', 'needs_recoding': ...",2611 CORRALITAS DR LOS ANGELES CA 90039,Residential,1990,"LAND DES IN DOC NO 60, 75-6-11 TRACT NO 4038 L...",1996,NaN,POINT (-118.25307 34.09921),85.0,Silver Lake

In [12]:
Echo_Park = gdf_2010_sjoin.loc[gdf_2010_sjoin['name'] == 'Echo Park']
Echo_Park = Echo_Park.drop(['index_right'], axis=1)
Echo_Park

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
475260,5152008014,90026-5833,34.06041609,-118.25776045,2010,43832,"{'latitude': '34.06041609', 'needs_recoding': ...",1267 W 2ND ST LOS ANGELES CA 90026,Commercial,1971,LOS ANGELES IMPROVEMENT COS SUB OF PART OF LOT...,1979,NaN,POINT (-118.25776 34.06042),27.0,Echo Park
475271,5152008016,90026-5833,34.06025317,-118.25758220,2010,199609,"{'latitude': '34.06025317', 'needs_recoding': ...",1261 W 2ND ST LOS ANGELES CA 90026,Commercial,1948,LOS ANGELES IMPROVEMENT COS SUB OF PART OF LOT...,2004,NaN,POINT (-118.25758 34.06025),27.0,Echo Park
475281,5152008019,90026-5833,34.05997663,-118.25742357,2010,19110,"{'latitude': '34.05997663', 'needs_recoding': ...",1245 W 2ND ST LOS ANGELES CA 90026,Residential,1920,LOS ANGELES IMPROVEMENT COS SUB OF PART OF LOT...,1975,NaN,POINT (-118.25742 34.05998),27.0,Echo Park
475285,5152008021,90026-5813,34.06004257,-118.25730458,2010,18034,"{'latitude': '34.06004257', 'needs_recoding': ...",117 S BIXEL ST LOS ANGELES CA 90026,Residential,1922,LOS ANGELES IMPROVEMENT COS SUB OF PART OF LOT...,1975,NaN,POINT (-118.25730 34.06004),27.0,Echo Park
475293,5152008013,90026-5833,34.06049756,-118.25784956,2010,265816,"{'latitude': '34.06049756', 'needs_recoding': ...",1273 W 2ND ST LOS ANGELES CA 90026,Commercial,1965,LOS ANGELES IMPROVEMENT COS SUB OF PART OF LOT...,1979,NaN,POINT (-118.25785 34.06050),27.0,Echo Park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536290,5443034007,90039-3714,34.09879045,-118.25012427,2010,111703,"{'latitude': '34.09879045', 'needs_recoding': ...",2010 SUNFLOWER AVE LOS ANGELES CA 90039,Residential,1942,SEMI TROPIC SPIRITUALISTS TRACT LOT 15 BLK 6,1985,NaN,POINT (-118.25012 34.09879),27.0,Echo Park
536291,5443034040,90039-3708,34.09793157,-118.24867157,2010,85122,"{'latitude': '34.09793157', 'needs_recoding': ...",1903 ROSEBUD AVE LOS ANGELES CA 90039,Residential,1951,SEMI TROPIC SPIRITUALISTS TRACT LOTS 46 AND LO...,1980,NaN,POINT (-118.24867 34.09793),27.0,Echo Park
536292,5443030020,90039-3715,34.09685223,-118.24962420,2010,362507,"{'latitude': '34.09685223', 'needs_recoding': ...",1909 WALCOTT WAY LOS ANGELES CA 90039,Residential,2007,SEMI TROPIC SPIRITUALISTS TRACT LOT COM N 89¢3...,1987,NaN,POINT (-118.24962 34.09685),27.0,Echo Park
536293,5443035014,90039-3707,34.09866725,-118.24913765,2010,1336076,"{'latitude': '34.09866725', 'needs_recoding': ...",2000 RIVERSIDE DR LOS ANGELES CA 90039,Commercial,1965,LOT 31 TR NO 458 AND POR OF LOT E JD AND ASA H...,1987,NaN,POINT (-118.24914 34.09867),27.0,Echo Park
536294,5443030015,90039-3715,34.09689235,-118.24994122,2010,208480,"{'latitude': '34.09689235', 'needs_recoding': ...",1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,1951,SEMI TROPIC SPIRITUALISTS TRACT LOT COM S 59¢4...,1996,NaN,POINT (-118.24994 34.09689),27.0,Echo Park

In [13]:
join1 = pd.concat([Westlake, Koreatown], axis=0).reset_index(drop=True)
join1

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,228886,"{'latitude': '34.05402081', 'needs_recoding': ...",953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,1960,CLARK AND BRYAN'S WESTMORELAND TRACT N 50 FT O...,2002,NaN,POINT (-118.28692 34.05402),107.0,Westlake
1,5076004042,90006,34.05416636,-118.28739291,2010,316201,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 204 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
2,5076004067,90006,34.05416636,-118.28739291,2010,442683,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 502 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
3,5076004028,90006,34.05416636,-118.28739291,2010,367397,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 110 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
4,5076004030,90006,34.05416636,-118.28739291,2010,433648,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 102 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13468,5518028018,90004-5785,34.07184366,-118.29380183,2010,95494,"{'latitude': '34.07184366', 'needs_recoding': ...",130 S BERENDO ST LOS ANGELES CA 90004,Residential,1922,AMBASSADOR HEIGHTS LOT 34,1975,NaN,POINT (-118.29380 34.07184),53.0,Koreatown
13469,5518032903,90004,34.07347937,-118.29206426,2010,0,"{'latitude': '34.07347937', 'needs_recoding': ...",121 N VERMONT AVE LOS ANGELES CA 90004,Commercial,1983,"LAND DESC AS PAR 4 IN DOC 513081,020305 POR OF...",2000,NaN,POINT (-118.29206 34.07348),53.0,Koreatown
13470,5518033001,90004-4817,34.07583322,-118.29207178,2010,700409,"{'latitude': '34.07583322', 'needs_recoding': ...",245 N VERMONT AVE LOS ANGELES CA 90004,Commercial,1926,TRACT # 6535 LOT 1,1988,NaN,POINT (-118.29207 34.07583),53.0,Koreatown
13471,5518033020,90004-4817,34.07481378,-118.29206852,2010,226550,"{'latitude': '34.07481378', 'needs_recoding': ...",207 N VERMONT AVE LOS ANGELES CA 90004,Commercial,1935,LOT COM N 0¢05'45'' W 63 FT FROM NW COR OF COU...,1975,NaN,POINT (-118.29207 34.07481),53.0,Koreatown
13472,5518031017,90004-5862,34.07190204,-118.29254813,2010,455434,"{'latitude': '34.07190204', 'needs_recoding': ...",124 S NEW HAMPSHIRE AVE LOS ANGELES CA 90004,Residential,1924,TRACT # 3611 LOT 37,1995,NaN,POINT (-118.29255 34.07190),53.0,Koreatown

In [15]:
join2 = pd.concat([join1,Pico_Union], axis=0).reset_index(drop=True)
join2

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,228886,"{'latitude': '34.05402081', 'needs_recoding': ...",953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,1960,CLARK AND BRYAN'S WESTMORELAND TRACT N 50 FT O...,2002,NaN,POINT (-118.28692 34.05402),107.0,Westlake
1,5076004042,90006,34.05416636,-118.28739291,2010,316201,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 204 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
2,5076004067,90006,34.05416636,-118.28739291,2010,442683,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 502 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
3,5076004028,90006,34.05416636,-118.28739291,2010,367397,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 110 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
4,5076004030,90006,34.05416636,-118.28739291,2010,433648,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 102 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16900,5137032032,90015-2022,34.04504895,-118.27623945,2010,162495,"{'latitude': '34.04504895', 'needs_recoding': ...","1236 S UNION AVE, 5 LOS ANGELES CA 90015",Residential,1988,TR=43990 LOT 1 CONDOMINIUM UNIT 5,1993,NaN,POINT (-118.27624 34.04505),74.0,Pico-Union
16901,5137032014,90015-2019,34.04469916,-118.27546600,2010,351483,"{'latitude': '34.04469916', 'needs_recoding': ...",1516 W 12TH PL LOS ANGELES CA 90015,Residential,1901,CITY CENTRE TRACT LOT 1 BLK 7,2006,NaN,POINT (-118.27547 34.04470),74.0,Pico-Union
16902,5137033030,90015-2409,34.04522940,-118.27749962,2010,929175,"{'latitude': '34.0452294', 'needs_recoding': F...",1619 W PICO BLVD LOS ANGELES CA 90015,Commercial,2005,WILLIAMSON TRACT LOTS 36 AND 37 BLK 7,2005,NaN,POINT (-118.27750 34.04523),74.0,Pico-Union
16903,5137032031,90015-2022,34.04504895,-118.27623945,2010,162297,"{'latitude': '34.04504895', 'needs_recoding': ...","1236 S UNION AVE, 4 LOS ANGELES CA 90015",Residential,1988,TR=43990 LOT 1 CONDOMINIUM UNIT 4,1989,NaN,POINT (-118.27624 34.04505),74.0,Pico-Union
16904,5137034003,90006-4175,34.04649126,-118.27985842,2010,175653,"{'latitude': '34.04649126', 'needs_recoding': ...",1242 S BONNIE BRAE ST LOS ANGELES CA 90006,Residential,1910,BONNIE BRAE PLACE LOT 6,1995,NaN,POINT (-118.27986 34.04649),74.0,Pico-Union

In [16]:
join3 = pd.concat([join2,Downtown], axis=0).reset_index(drop=True)
join3

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,228886,"{'latitude': '34.05402081', 'needs_recoding': ...",953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,1960,CLARK AND BRYAN'S WESTMORELAND TRACT N 50 FT O...,2002,NaN,POINT (-118.28692 34.05402),107.0,Westlake
1,5076004042,90006,34.05416636,-118.28739291,2010,316201,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 204 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
2,5076004067,90006,34.05416636,-118.28739291,2010,442683,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 502 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
3,5076004028,90006,34.05416636,-118.28739291,2010,367397,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 110 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
4,5076004030,90006,34.05416636,-118.28739291,2010,433648,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 102 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28069,5409024165,90012,34.05720539,-118.23537796,2010,184538,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 542 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 542 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
28070,5409024160,90012,34.05720539,-118.23537796,2010,184538,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 537 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 537 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
28071,5409024163,90012,34.05720539,-118.23537796,2010,178960,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 540 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 540 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
28072,5409024161,90012,34.05720539,-118.23537796,2010,184538,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 538 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 538 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown
28073,5409024162,90012,34.05720539,-118.23537796,2010,273089,"{'latitude': '34.05720539', 'needs_recoding': ...","888 N ALAMEDA ST, NO 539 LOS ANGELES CA 90012",Residential,2006,TR=61848 LOT 1 CONDO UNIT 539 (AIRSPACE AND 1/...,2010,NaN,POINT (-118.23538 34.05721),24.0,Downtown

In [17]:
join4 = pd.concat([join3,Silver_Lake], axis=0).reset_index(drop=True)
join4

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,228886,"{'latitude': '34.05402081', 'needs_recoding': ...",953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,1960,CLARK AND BRYAN'S WESTMORELAND TRACT N 50 FT O...,2002,NaN,POINT (-118.28692 34.05402),107.0,Westlake
1,5076004042,90006,34.05416636,-118.28739291,2010,316201,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 204 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
2,5076004067,90006,34.05416636,-118.28739291,2010,442683,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 502 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
3,5076004028,90006,34.05416636,-118.28739291,2010,367397,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 110 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
4,5076004030,90006,34.05416636,-118.28739291,2010,433648,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 102 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35396,5440031025,90039-4002,34.10012836,-118.25236922,2010,641000,"{'latitude': '34.10012836', 'needs_recoding': ...",2559 CORRALITAS DR LOS ANGELES CA 90039,Residential,1929,TRACT NO 4038 LOT 30,2006,NaN,POINT (-118.25237 34.10013),85.0,Silver Lake
35397,5440028009,90039-4052,34.09932685,-118.25340760,2010,480945,"{'latitude': '34.09932685', 'needs_recoding': ...",2592 CORRALITAS DR LOS ANGELES CA 90039,Residential,1991,"LAND DES IN DOC NO 91, 75-6-11 TRACT NO 4038 L...",2001,NaN,POINT (-118.25341 34.09933),85.0,Silver Lake
35398,5440029022,90039-4003,34.10057287,-118.25223323,2010,272234,"{'latitude': '34.10057287', 'needs_recoding': ...",2552 CORRALITAS DR LOS ANGELES CA 90039,Residential,1983,TRACT NO 4038 LOT 52,1987,NaN,POINT (-118.25223 34.10057),85.0,Silver Lake
35399,5440026016,90039-4010,34.10136602,-118.25299794,2010,770000,"{'latitude': '34.10136602', 'needs_recoding': ...",2448 RIVERSIDE PL LOS ANGELES CA 90039,Residential,1960,TRACT # 6688 LOT 11,2010,NaN,POINT (-118.25300 34.10137),85.0,Silver Lake
35400,5440031032,90039-4004,34.09920993,-118.25306676,2010,359062,"{'latitude': '34.09920993', 'needs_recoding': ...",2611 CORRALITAS DR LOS ANGELES CA 90039,Residential,1990,"LAND DES IN DOC NO 60, 75-6-11 TRACT NO 4038 L...",1996,NaN,POINT (-118.25307 34.09921),85.0,Silver Lake

In [18]:
finaljoin = pd.concat([join4,Echo_Park], axis=0).reset_index(drop=True)
finaljoin

,ain,situszip,center_lat,center_lon,rollyear,roll_totalvalue,location_1,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,situscity,geometry,OBJECTID,name
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,228886,"{'latitude': '34.05402081', 'needs_recoding': ...",953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,1960,CLARK AND BRYAN'S WESTMORELAND TRACT N 50 FT O...,2002,NaN,POINT (-118.28692 34.05402),107.0,Westlake
1,5076004042,90006,34.05416636,-118.28739291,2010,316201,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 204 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
2,5076004067,90006,34.05416636,-118.28739291,2010,442683,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 502 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
3,5076004028,90006,34.05416636,-118.28739291,2010,367397,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 110 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
4,5076004030,90006,34.05416636,-118.28739291,2010,433648,"{'latitude': '34.05416636', 'needs_recoding': ...","940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 102 (AIRSPACE AND 1/4...,2008,NaN,POINT (-118.28739 34.05417),107.0,Westlake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41149,5443034007,90039-3714,34.09879045,-118.25012427,2010,111703,"{'latitude': '34.09879045', 'needs_recoding': ...",2010 SUNFLOWER AVE LOS ANGELES CA 90039,Residential,1942,SEMI TROPIC SPIRITUALISTS TRACT LOT 15 BLK 6,1985,NaN,POINT (-118.25012 34.09879),27.0,Echo Park
41150,5443034040,90039-3708,34.09793157,-118.24867157,2010,85122,"{'latitude': '34.09793157', 'needs_recoding': ...",1903 ROSEBUD AVE LOS ANGELES CA 90039,Residential,1951,SEMI TROPIC SPIRITUALISTS TRACT LOTS 46 AND LO...,1980,NaN,POINT (-118.24867 34.09793),27.0,Echo Park
41151,5443030020,90039-3715,34.09685223,-118.24962420,2010,362507,"{'latitude': '34.09685223', 'needs_recoding': ...",1909 WALCOTT WAY LOS ANGELES CA 90039,Residential,2007,SEMI TROPIC SPIRITUALISTS TRACT LOT COM N 89¢3...,1987,NaN,POINT (-118.24962 34.09685),27.0,Echo Park
41152,5443035014,90039-3707,34.09866725,-118.24913765,2010,1336076,"{'latitude': '34.09866725', 'needs_recoding': ...",2000 RIVERSIDE DR LOS ANGELES CA 90039,Commercial,1965,LOT 31 TR NO 458 AND POR OF LOT E JD AND ASA H...,1987,NaN,POINT (-118.24914 34.09867),27.0,Echo Park
41153,5443030015,90039-3715,34.09689235,-118.24994122,2010,208480,"{'latitude': '34.09689235', 'needs_recoding': ...",1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,1951,SEMI TROPIC SPIRITUALISTS TRACT LOT COM S 59¢4...,1996,NaN,POINT (-118.24994 34.09689),27.0,Echo Park

In [19]:
tract = gpd.read_file('/Users/jinglanlin/Desktop/School/01 UCLA/04 Spring 2022/UP 229 DS/Github/UDS-Project--Full-Team-/Data/Census_Tracts_2020.geojson')
tract.head()

,OBJECTID,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
0,1,101110,1011.10,1.229562e+07,15083.854287,"POLYGON ((-118.28491 34.25948, -118.28492 34.2..."
1,2,101122,1011.22,2.845774e+07,31671.455844,"POLYGON ((-118.29015 34.27417, -118.29015 34.2..."
2,3,101220,1012.20,7.522093e+06,12698.783810,"POLYGON ((-118.28100 34.25592, -118.28198 34.2..."
3,4,101221,1012.21,3.812000e+06,9161.710543,"POLYGON ((-118.28735 34.25591, -118.28863 34.2..."
4,5,101222,1012.22,3.191371e+06,9980.600461,"POLYGON ((-118.28594 34.25405, -118.28594 34.2..."

In [5]:
gdf_2010_sjoin = gpd.sjoin(finaljoin,tract.to_crs('EPSG:4326'),how="left", predicate='intersects')
gdf_2010_sjoin

,situszip,taxratearea_city,ain,rollyear,taxratearea,assessorid,propertylocation,usetype,usecode,usecodedescchar1,...,usecodedescchar3,parcelclassification,situsfraction,geometry,index_right,OBJECTID,CT20,LABEL,ShapeSTArea,ShapeSTLength
0,90005-1170,LOS ANGELES,5077016026,2019,06657,5077-016-026,731 MAGNOLIA AVE LOS ANGELES CA 90005,VAC,010V,Residential,...,NaN,NaN,NaN,POINT (-118.28637 34.05905),664.0,665.0,212204,2122.04,2.294673e+06,6149.261568
1,90005-1225,LOS ANGELES,5077021004,2019,00067,5077-021-004,2730 W 8TH ST LOS ANGELES CA 90005,VAC,010V,Residential,...,NaN,NaN,NaN,POINT (-118.28510 34.05746),662.0,663.0,212202,2122.02,2.222403e+06,6482.090647
2,90005-2333,LOS ANGELES,5094003013,2019,06657,5094-003-013,715 IROLO ST LOS ANGELES CA 90005,SFR,0100,Residential,...,NaN,NaN,NaN,POINT (-118.30123 34.05924),669.0,670.0,212410,2124.10,1.691953e+06,5550.696624
3,90005-3268,LOS ANGELES,5504017027,2019,00067,5504-017-027,"601 S VAN NESS AVE, 6 LOS ANGELES CA 90005",CND,010C,Residential,...,NaN,NaN,NaN,POINT (-118.31574 34.06290),651.0,652.0,211701,2117.01,7.012738e+06,10536.811438
4,90005-3841,LOS ANGELES,5505007005,2019,00067,5505-007-005,634 S RIMPAU BLVD LOS ANGELES CA 90005,SFR,0101,Residential,...,NaN,NaN,NaN,POINT (-118.33121 34.06301),639.0,640.0,211000,2110.00,2.859668e+07,25170.331758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135973,90010-3814,LOS ANGELES,5507017140,2021,00067,5507-017-140,"4801 WILSHIRE BLVD, NO 320 LOS ANGELES CA 90010",C/I,170C,Commercial,...,NaN,NaN,NaN,POINT (-118.33507 34.06237),639.0,640.0,211000,2110.00,2.859668e+07,25170.331758
135974,90010-2895,LOS ANGELES,5503030180,2021,06657,5503-030-180,"3785 WILSHIRE BLVD, NO 2106 LOS ANGELES CA ...",CND,01HC,Residential,...,High Rise 5 Stories or More,NaN,NaN,POINT (-118.30872 34.06278),654.0,655.0,211802,2118.02,3.502699e+06,7938.572086
135975,90010-2892,LOS ANGELES,5503030138,2021,06657,5503-030-138,"3785 WILSHIRE BLVD, NO 1712 LOS ANGELES CA ...",CND,01HC,Residential,...,High Rise 5 Stories or More,NaN,NaN,POINT (-118.30872 34.06278),654.0,655.0,211802,2118.02,3.502699e+06,7938.572086
135976,90010,LOS ANGELES,5503030048,2021,06657,5503-030-048,"3785 WILSHIRE BLVD, NO 806 LOS ANGELES CA ...",CND,01HC,Residential,...,High Rise 5 Stories or More,NaN,NaN,POINT (-118.30872 34.06278),654.0,655.0,211802,2118.02,3.502699e+06,7938.572086
135977,90010,LOS ANGELES,6061012032,2021,00212,6061-012-032,702 W 104TH PL LOS ANGELES CA 90010,R-I,0400,Residential,...,4 Stories or Less,NaN,NaN,POINT (-118.28726 33.94133),897.0,898.0,241201,2412.01,5.230365e+06,10180.375520

In [7]:
gdf_ktown_sjoin.drop('index_right',inplace=True, axis=1)

In [9]:
gdf_ktown_sjoin2 = gpd.sjoin(gdf_ktown_sjoin,nb.to_crs('EPSG:4326'),how="left", predicate='intersects')
gdf_ktown_sjoin2

,situszip,taxratearea_city,ain,rollyear,taxratearea,assessorid,propertylocation,usetype,usecode,usecodedescchar1,...,situsfraction,geometry,OBJECTID_left,CT20,LABEL,ShapeSTArea,ShapeSTLength,index_right,OBJECTID_right,name
0,90005-1170,LOS ANGELES,5077016026,2019,06657,5077-016-026,731 MAGNOLIA AVE LOS ANGELES CA 90005,VAC,010V,Residential,...,NaN,POINT (-118.28637 34.05905),665.0,212204,2122.04,2.294673e+06,6149.261568,106.0,107.0,Westlake
1,90005-1225,LOS ANGELES,5077021004,2019,00067,5077-021-004,2730 W 8TH ST LOS ANGELES CA 90005,VAC,010V,Residential,...,NaN,POINT (-118.28510 34.05746),663.0,212202,2122.02,2.222403e+06,6482.090647,106.0,107.0,Westlake
2,90005-2333,LOS ANGELES,5094003013,2019,06657,5094-003-013,715 IROLO ST LOS ANGELES CA 90005,SFR,0100,Residential,...,NaN,POINT (-118.30123 34.05924),670.0,212410,2124.10,1.691953e+06,5550.696624,52.0,53.0,Koreatown
3,90005-3268,LOS ANGELES,5504017027,2019,00067,5504-017-027,"601 S VAN NESS AVE, 6 LOS ANGELES CA 90005",CND,010C,Residential,...,NaN,POINT (-118.31574 34.06290),652.0,211701,2117.01,7.012738e+06,10536.811438,110.0,111.0,Windsor Square
4,90005-3841,LOS ANGELES,5505007005,2019,00067,5505-007-005,634 S RIMPAU BLVD LOS ANGELES CA 90005,SFR,0101,Residential,...,NaN,POINT (-118.33121 34.06301),640.0,211000,2110.00,2.859668e+07,25170.331758,39.0,40.0,Hancock Park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135973,90010-3814,LOS ANGELES,5507017140,2021,00067,5507-017-140,"4801 WILSHIRE BLVD, NO 320 LOS ANGELES CA 90010",C/I,170C,Commercial,...,NaN,POINT (-118.33507 34.06237),640.0,211000,2110.00,2.859668e+07,25170.331758,39.0,40.0,Hancock Park
135974,90010-2895,LOS ANGELES,5503030180,2021,06657,5503-030-180,"3785 WILSHIRE BLVD, NO 2106 LOS ANGELES CA ...",CND,01HC,Residential,...,NaN,POINT (-118.30872 34.06278),655.0,211802,2118.02,3.502699e+06,7938.572086,52.0,53.0,Koreatown
135975,90010-2892,LOS ANGELES,5503030138,2021,06657,5503-030-138,"3785 WILSHIRE BLVD, NO 1712 LOS ANGELES CA ...",CND,01HC,Residential,...,NaN,POINT (-118.30872 34.06278),655.0,211802,2118.02,3.502699e+06,7938.572086,52.0,53.0,Koreatown
135976,90010,LOS ANGELES,5503030048,2021,06657,5503-030-048,"3785 WILSHIRE BLVD, NO 806 LOS ANGELES CA ...",CND,01HC,Residential,...,NaN,POINT (-118.30872 34.06278),655.0,211802,2118.02,3.502699e+06,7938.572086,52.0,53.0,Koreatown
135977,90010,LOS ANGELES,6061012032,2021,00212,6061-012-032,702 W 104TH PL LOS ANGELES CA 90010,R-I,0400,Residential,...,NaN,POINT (-118.28726 33.94133),898.0,241201,2412.01,5.230365e+06,10180.375520,101.0,102.0,Vermont Vista