In [1]:
import json
import pandas as pd
import geopandas as gpd

gdf_2010 = gpd.read_file('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/landvalue_2010_new.geojson')
#gdf_2010 = gdf_2010.rename(columns={'roll_totalvalue': 'roll_totalvalue_2010'})
#gdf_2010.set_index('ain',inplace=True)
gdf_2010

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,location_1,OBJECTID_left,neighborhood,index_right,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,227767,0,2002,953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,...,"{'latitude': '34.05402081', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28692 34.05402)
1,5076004042,90006,34.05416636,-118.28739291,2010,58918,1050,2010,"940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
2,5076004067,90006,34.05416636,-118.28739291,2010,82485,1470,2010,"940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
3,5076004028,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
4,5076004030,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41149,5443034007,90039-3714,34.09879045,-118.25012427,2010,47196,1344,1985,2010 SUNFLOWER AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09879045', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25012 34.09879)
41150,5443034040,90039-3708,34.09793157,-118.24867157,2010,44712,897,1980,1903 ROSEBUD AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09793157', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24867 34.09793)
41151,5443030020,90039-3715,34.09685223,-118.24962420,2010,50203,2818,2007,1909 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09685223', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24962 34.09685)
41152,5443035014,90039-3707,34.09866725,-118.24913765,2010,549257,12377,1987,2000 RIVERSIDE DR LOS ANGELES CA 90039,Commercial,...,"{'latitude': '34.09866725', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24914 34.09867)
41153,5443030015,90039-3715,34.09689235,-118.24994122,2010,140148,1115,1996,1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09689235', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24994 34.09689)

In [2]:
gdf_2010.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 41154 entries, 0 to 41153
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ain                        41154 non-null  object
 1   situszip                   41154 non-null  object
 2   center_lat                 41154 non-null  object
 3   center_lon                 41154 non-null  object
 4   rollyear                   41154 non-null  object
 5   roll_landvalue             41154 non-null  object
 6   sqftmain                   41154 non-null  object
 7   roll_impbaseyear           41154 non-null  object
 8   propertylocation           41154 non-null  object
 9   usecodedescchar1           41144 non-null  object
 10  effectiveyearbuilt         41154 non-null  object
 11  parcelboundarydescription  41154 non-null  object
 12  roll_landbaseyear          41154 non-null  object
 13  location_1                 41154 non-null  object
 14  OBJECTID_left              41154 non-null  float64
 15  neighborhood               41154 non-null  object
 16  index_right                41154 non-null  int64
 17  OBJECTID_right             41154 non-null  int64
 18  CT20                       41154 non-null  object
 19  LABEL                      41154 non-null  object
 20  ShapeSTArea                41154 non-null  float64
 21  ShapeSTLength              41154 non-null  float64
 22  geometry                   41154 non-null  geometry
dtypes: float64(3), geometry(1), int64(2), object(17)
memory usage: 7.2+ MB

In [3]:
gdf_2010.query('roll_landbaseyear == "2010"').roll_landbaseyear.count()

2186

In [4]:
gdf_2010_sold = gdf_2010[gdf_2010["roll_landbaseyear"] == '2010']
gdf_2010_sold

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,location_1,OBJECTID_left,neighborhood,index_right,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,"{'latitude': '34.05337712', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28456 34.05338)
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,"{'latitude': '34.06108702', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28444 34.06109)
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,"{'latitude': '34.061326', 'needs_recoding': Fa...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28568 34.06133)
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,"{'latitude': '34.06050239', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28605 34.06050)
191,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,"{'latitude': '34.06129452', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28501 34.06129)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40896,5443007007,90039-3946,34.09445414,-118.25052874,2010,392000,1208,2010,1964 LANDA ST LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09445414', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25053 34.09445)
41008,5443015013,90026-2053,34.09343035,-118.24598410,2010,396000,920,2010,2427 VALENTINE ST LOS ANGELES CA 90026,Residential,...,"{'latitude': '34.09343035', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24598 34.09343)
41086,5443027028,90039-3735,34.09648201,-118.24958644,2010,525000,888,2010,1908 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09648201', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24959 34.09648)
41107,5443028027,90039-3731,34.09575278,-118.25177910,2010,258600,1068,2010,1941 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09575278', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25178 34.09575)
41121,5443028035,90039-3739,34.09586083,-118.25144462,2010,365000,517,2010,2355 PERU ST LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09586083', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25144 34.09586)

In [5]:
min_number = min(gdf_2010_sold.ain)
print(min_number)

5056001017

In [6]:
max_number = max(gdf_2010_sold.ain)
print(max_number)

5518033027

In [7]:
#import parcel data
import requests
import json


url = 'https://data.lacounty.gov/resource/rjze-ndj2.json?$where=within_box(the_geom, 34.1164, -118.3217, 34.01333, -118.2675)&$limit=100000' # copied and pasted from the webpage
r = requests.get(url)
parcel = pd.DataFrame(json.loads(r.text))
parcel

#south:34.013339055368384, -118.23277272855023
#north: 34.11633386937314, -118.2674474941663
#eaast:34.01604254848126, -118.2217864006906
#west: 34.05453104173829, -118.32179797239648
#https://data.cityofchicago.org/resource/yama-9had.json?$where=within_polygon(the_geom, 'MULTIPOLYGON (((34.1037 -118.2484, 34.0054 -118.2455, 34.0545 -118.2062, 34.0633 -118.3351)))')
#within_polygon(location, 'MULTIPOLYGON (((34.10378510012116, -118.24846458486526, 34.00549184389096, -118.24552614565691, 34.05450056185422, -118.20622452124513, 34.06332521000708, -118.33514854151177)))')
#$where=ain>5056000000.0&$limit=2500000
#requestString = 'https://data.lacounty.gov/resource/rjze-ndj2.json&$limit=2100000'
#r = requests.get(requestString)
#d = json.loads(r.text)
#parcel = pd.DataFrame(d)
#parcel

,the_geom,lon_coord,ain,lat_coord,x_coord,y_coord,shape_area,shape_len
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32052234,5052003001,34.02944719,6464550.25589,1833253.40852,4118.85839844,268.710312492
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036613,5052003002,34.0294473,6464597.58649,1833253.29705,4118.71191406,268.700285953
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036544,5052003004,34.02927138,6464597.59358,1833189.27834,5822.9453125,366.020815496
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036271,5052003010,34.02859509,6464597.635,1832943.16,5821.99609375,366.000915114
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036179,5052003012,34.02836261,6464597.645,1832858.555,6561.81738281,376.420914855
...,...,...,...,...,...,...,...,...
52251,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29500987,5540014010,34.09448939,6472349.83528,1856899.75435,17708.1816406,537.983233013
52252,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.2942414,5540015005,34.094516,6472582.52329,1856908.75437,9905.31347656,485.910341354
52253,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29424216,5540016010,34.09423002,6472581.98691,1856804.68404,10059.3476563,487.292871966
52254,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29465601,5540023002,34.09311708,6472455.505,1856400.03,6749.98144531,370.00250984
52255,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.295756,5540026006,34.09132439,6472120.54739,1855748.61818,7204.76464844,388.192655311

In [8]:
parcel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52256 entries, 0 to 52255
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   the_geom    52256 non-null  object
 1   lon_coord   52256 non-null  object
 2   ain         52248 non-null  object
 3   lat_coord   52256 non-null  object
 4   x_coord     52256 non-null  object
 5   y_coord     52256 non-null  object
 6   shape_area  52256 non-null  object
 7   shape_len   52256 non-null  object
dtypes: object(8)
memory usage: 3.2+ MB

In [9]:
parcelgdf = gpd.GeoDataFrame(
    parcel, geometry=gpd.points_from_xy(parcel.lon_coord, parcel.lat_coord, 
                                          crs='EPSG:4326'))
parcelgdf

,the_geom,lon_coord,ain,lat_coord,x_coord,y_coord,shape_area,shape_len,geometry
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32052234,5052003001,34.02944719,6464550.25589,1833253.40852,4118.85839844,268.710312492,POINT (-118.32052 34.02945)
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036613,5052003002,34.0294473,6464597.58649,1833253.29705,4118.71191406,268.700285953,POINT (-118.32037 34.02945)
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036544,5052003004,34.02927138,6464597.59358,1833189.27834,5822.9453125,366.020815496,POINT (-118.32037 34.02927)
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036271,5052003010,34.02859509,6464597.635,1832943.16,5821.99609375,366.000915114,POINT (-118.32036 34.02860)
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036179,5052003012,34.02836261,6464597.645,1832858.555,6561.81738281,376.420914855,POINT (-118.32036 34.02836)
...,...,...,...,...,...,...,...,...,...
52251,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29500987,5540014010,34.09448939,6472349.83528,1856899.75435,17708.1816406,537.983233013,POINT (-118.29501 34.09449)
52252,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.2942414,5540015005,34.094516,6472582.52329,1856908.75437,9905.31347656,485.910341354,POINT (-118.29424 34.09452)
52253,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29424216,5540016010,34.09423002,6472581.98691,1856804.68404,10059.3476563,487.292871966,POINT (-118.29424 34.09423)
52254,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29465601,5540023002,34.09311708,6472455.505,1856400.03,6749.98144531,370.00250984,POINT (-118.29466 34.09312)
52255,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.295756,5540026006,34.09132439,6472120.54739,1855748.61818,7204.76464844,388.192655311,POINT (-118.29576 34.09132)

In [10]:
parcelgdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 52256 entries, 0 to 52255
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   the_geom    52256 non-null  object
 1   lon_coord   52256 non-null  object
 2   ain         52248 non-null  object
 3   lat_coord   52256 non-null  object
 4   x_coord     52256 non-null  object
 5   y_coord     52256 non-null  object
 6   shape_area  52256 non-null  object
 7   shape_len   52256 non-null  object
 8   geometry    52256 non-null  geometry
dtypes: geometry(1), object(8)
memory usage: 3.6+ MB

In [11]:
gdf_2010_sold.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Int64Index: 2186 entries, 110 to 41121
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ain                        2186 non-null   object
 1   situszip                   2186 non-null   object
 2   center_lat                 2186 non-null   object
 3   center_lon                 2186 non-null   object
 4   rollyear                   2186 non-null   object
 5   roll_landvalue             2186 non-null   object
 6   sqftmain                   2186 non-null   object
 7   roll_impbaseyear           2186 non-null   object
 8   propertylocation           2186 non-null   object
 9   usecodedescchar1           2183 non-null   object
 10  effectiveyearbuilt         2186 non-null   object
 11  parcelboundarydescription  2186 non-null   object
 12  roll_landbaseyear          2186 non-null   object
 13  location_1                 2186 non-null   object
 14  OBJECTID_left              2186 non-null   float64
 15  neighborhood               2186 non-null   object
 16  index_right                2186 non-null   int64
 17  OBJECTID_right             2186 non-null   int64
 18  CT20                       2186 non-null   object
 19  LABEL                      2186 non-null   object
 20  ShapeSTArea                2186 non-null   float64
 21  ShapeSTLength              2186 non-null   float64
 22  geometry                   2186 non-null   geometry
dtypes: float64(3), geometry(1), int64(2), object(17)
memory usage: 409.9+ KB

In [12]:
gdf_2010_sold = gdf_2010_sold.drop(columns=['index_right'])
gdf_2010_sold

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,roll_landbaseyear,location_1,OBJECTID_left,neighborhood,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,2010,"{'latitude': '34.05337712', 'needs_recoding': ...",107.0,Westlake,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28456 34.05338)
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,2010,"{'latitude': '34.06108702', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28444 34.06109)
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.061326', 'needs_recoding': Fa...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28568 34.06133)
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,2010,"{'latitude': '34.06050239', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28605 34.06050)
191,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.06129452', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28501 34.06129)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40896,5443007007,90039-3946,34.09445414,-118.25052874,2010,392000,1208,2010,1964 LANDA ST LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09445414', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25053 34.09445)
41008,5443015013,90026-2053,34.09343035,-118.24598410,2010,396000,920,2010,2427 VALENTINE ST LOS ANGELES CA 90026,Residential,...,2010,"{'latitude': '34.09343035', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24598 34.09343)
41086,5443027028,90039-3735,34.09648201,-118.24958644,2010,525000,888,2010,1908 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09648201', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24959 34.09648)
41107,5443028027,90039-3731,34.09575278,-118.25177910,2010,258600,1068,2010,1941 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09575278', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25178 34.09575)
41121,5443028035,90039-3739,34.09586083,-118.25144462,2010,365000,517,2010,2355 PERU ST LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09586083', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25144 34.09586)

In [13]:
joinedgdf2010=gpd.sjoin(gdf_2010_sold.to_crs('EPSG:4326'),parcelgdf.to_crs('EPSG:4326'),how='left')
joinedgdf2010

,ain_left,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,geometry,index_right,the_geom,lon_coord,ain_right,lat_coord,x_coord,y_coord,shape_area,shape_len
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,POINT (-118.28456 34.05338),48427.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28455814,5076006006,34.05337712,6475471.82332,1841929.1484,13521.4472656,470.334649481
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,POINT (-118.28444 34.06109),50431.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28444197,5077013035,34.06108702,6475514.95251,1844734.81795,8855.33203125,415.074878377
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,POINT (-118.28568 34.06133),50517.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28567752,5077013036,34.061326,6475140.9776,1844822.84926,19059.2460938,746.648966648
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,POINT (-118.28605 34.06050),50476.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28604757,5077014048,34.06050239,6475028.04528,1844523.44255,6830.42871094,393.57457948
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,POINT (-118.28605 34.06050),50526.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28604757,5077014053,34.06050239,6475028.04528,1844523.44255,6830.42871094,393.57457948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40896,5443007007,90039-3946,34.09445414,-118.25052874,2010,392000,1208,2010,1964 LANDA ST LOS ANGELES CA 90039,Residential,...,POINT (-118.25053 34.09445),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41008,5443015013,90026-2053,34.09343035,-118.24598410,2010,396000,920,2010,2427 VALENTINE ST LOS ANGELES CA 90026,Residential,...,POINT (-118.24598 34.09343),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41086,5443027028,90039-3735,34.09648201,-118.24958644,2010,525000,888,2010,1908 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,POINT (-118.24959 34.09648),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41107,5443028027,90039-3731,34.09575278,-118.25177910,2010,258600,1068,2010,1941 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,POINT (-118.25178 34.09575),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41121,5443028035,90039-3739,34.09586083,-118.25144462,2010,365000,517,2010,2355 PERU ST LOS ANGELES CA 90039,Residential,...,POINT (-118.25144 34.09586),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
gdf_2010_sold

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,roll_landbaseyear,location_1,OBJECTID_left,neighborhood,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,2010,"{'latitude': '34.05337712', 'needs_recoding': ...",107.0,Westlake,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28456 34.05338)
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,2010,"{'latitude': '34.06108702', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28444 34.06109)
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.061326', 'needs_recoding': Fa...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28568 34.06133)
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,2010,"{'latitude': '34.06050239', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28605 34.06050)
191,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.06129452', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28501 34.06129)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40896,5443007007,90039-3946,34.09445414,-118.25052874,2010,392000,1208,2010,1964 LANDA ST LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09445414', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25053 34.09445)
41008,5443015013,90026-2053,34.09343035,-118.24598410,2010,396000,920,2010,2427 VALENTINE ST LOS ANGELES CA 90026,Residential,...,2010,"{'latitude': '34.09343035', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24598 34.09343)
41086,5443027028,90039-3735,34.09648201,-118.24958644,2010,525000,888,2010,1908 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09648201', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24959 34.09648)
41107,5443028027,90039-3731,34.09575278,-118.25177910,2010,258600,1068,2010,1941 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09575278', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25178 34.09575)
41121,5443028035,90039-3739,34.09586083,-118.25144462,2010,365000,517,2010,2355 PERU ST LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09586083', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25144 34.09586)

In [15]:
join2010 = gdf_2010_sold.merge(parcelgdf, how='left',on='ain')
join2010 = join2010.dropna()
join2010

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,ShapeSTLength,geometry_x,the_geom,lon_coord,lat_coord,x_coord,y_coord,shape_area,shape_len,geometry_y
0,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,6327.274225,POINT (-118.28456 34.05338),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28455814,34.05337712,6475471.82332,1841929.1484,13521.4472656,470.334649481,POINT (-118.28456 34.05338)
1,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,6149.261568,POINT (-118.28444 34.06109),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28444197,34.06108702,6475514.95251,1844734.81795,8855.33203125,415.074878377,POINT (-118.28444 34.06109)
2,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,6149.261568,POINT (-118.28568 34.06133),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28567752,34.061326,6475140.9776,1844822.84926,19059.2460938,746.648966648,POINT (-118.28568 34.06133)
3,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,6149.261568,POINT (-118.28605 34.06050),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28604757,34.06050239,6475028.04528,1844523.44255,6830.42871094,393.57457948,POINT (-118.28605 34.06050)
4,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,6149.261568,POINT (-118.28501 34.06129),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28500965,34.06129452,6475343.22777,1844810.81772,100532.499023,1343.89410917,POINT (-118.28501 34.06129)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,5402028009,90026-4022,34.07621231,-118.26869364,2010,300000,1678,2010,810 CORONADO TER LOS ANGELES CA 90026,Residential,...,9761.838870,POINT (-118.26869 34.07621),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26869434,34.07621263,6480299.29371,1850226.17628,5731.46777344,329.140692477,POINT (-118.26869 34.07621)
2169,5424018007,90026-2322,34.08223393,-118.26787100,2010,388000,1066,2010,1326 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,11167.787060,POINT (-118.26787 34.08223),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.267871,34.08223393,6480554.46136,1852416.77032,4797.51367188,319.884103451,POINT (-118.26787 34.08223)
2170,5424017011,90026-2215,34.08301413,-118.26851995,2010,639200,1968,2010,1342 N BENTON WAY LOS ANGELES CA 90026,Residential,...,11167.787060,POINT (-118.26852 34.08301),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26851995,34.08301413,6480358.71324,1852701.22073,5209.87402344,340.536942721,POINT (-118.26852 34.08301)
2171,5424016027,90026-2323,34.08339106,-118.26781974,2010,503000,2052,2010,1407 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,11167.787060,POINT (-118.26782 34.08339),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26781974,34.08339106,6480571.10326,1852837.82668,4798.84570313,319.987066318,POINT (-118.26782 34.08339)
2174,5424017010,90026-2215,34.08291563,-118.26857864,2010,553000,1369,2010,1338 N BENTON WAY LOS ANGELES CA 90026,Residential,...,11167.787060,POINT (-118.26858 34.08292),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26857864,34.08291563,6480340.84678,1852665.42276,5153.58007813,337.691828565,POINT (-118.26858 34.08292)

In [16]:
join2010.query('neighborhood == "Westlake"').neighborhood.count()

116

In [17]:
join2010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 962 entries, 0 to 2174
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ain                        962 non-null    object
 1   situszip                   962 non-null    object
 2   center_lat                 962 non-null    object
 3   center_lon                 962 non-null    object
 4   rollyear                   962 non-null    object
 5   roll_landvalue             962 non-null    object
 6   sqftmain                   962 non-null    object
 7   roll_impbaseyear           962 non-null    object
 8   propertylocation           962 non-null    object
 9   usecodedescchar1           962 non-null    object
 10  effectiveyearbuilt         962 non-null    object
 11  parcelboundarydescription  962 non-null    object
 12  roll_landbaseyear          962 non-null    object
 13  location_1                 962 non-null    object
 14  OBJECTID_left              962 non-null    float64
 15  neighborhood               962 non-null    object
 16  OBJECTID_right             962 non-null    int64
 17  CT20                       962 non-null    object
 18  LABEL                      962 non-null    object
 19  ShapeSTArea                962 non-null    float64
 20  ShapeSTLength              962 non-null    float64
 21  geometry_x                 962 non-null    geometry
 22  the_geom                   962 non-null    object
 23  lon_coord                  962 non-null    object
 24  lat_coord                  962 non-null    object
 25  x_coord                    962 non-null    object
 26  y_coord                    962 non-null    object
 27  shape_area                 962 non-null    object
 28  shape_len                  962 non-null    object
 29  geometry_y                 962 non-null    geometry
dtypes: float64(3), geometry(2), int64(1), object(24)
memory usage: 233.0+ KB

In [18]:
#join2010['roll_landvalue'].astype(float)
#join2010['shape_area'].astype(float)
join2010['shape_area'] = pd.to_numeric(join2010['shape_area'])
join2010['roll_landvalue'] = pd.to_numeric(join2010['roll_landvalue'])

In [19]:
join2010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 962 entries, 0 to 2174
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ain                        962 non-null    object
 1   situszip                   962 non-null    object
 2   center_lat                 962 non-null    object
 3   center_lon                 962 non-null    object
 4   rollyear                   962 non-null    object
 5   roll_landvalue             962 non-null    int64
 6   sqftmain                   962 non-null    object
 7   roll_impbaseyear           962 non-null    object
 8   propertylocation           962 non-null    object
 9   usecodedescchar1           962 non-null    object
 10  effectiveyearbuilt         962 non-null    object
 11  parcelboundarydescription  962 non-null    object
 12  roll_landbaseyear          962 non-null    object
 13  location_1                 962 non-null    object
 14  OBJECTID_left              962 non-null    float64
 15  neighborhood               962 non-null    object
 16  OBJECTID_right             962 non-null    int64
 17  CT20                       962 non-null    object
 18  LABEL                      962 non-null    object
 19  ShapeSTArea                962 non-null    float64
 20  ShapeSTLength              962 non-null    float64
 21  geometry_x                 962 non-null    geometry
 22  the_geom                   962 non-null    object
 23  lon_coord                  962 non-null    object
 24  lat_coord                  962 non-null    object
 25  x_coord                    962 non-null    object
 26  y_coord                    962 non-null    object
 27  shape_area                 962 non-null    float64
 28  shape_len                  962 non-null    object
 29  geometry_y                 962 non-null    geometry
dtypes: float64(4), geometry(2), int64(2), object(22)
memory usage: 233.0+ KB

In [20]:
join2010['landvalue_sqft']=join2010['roll_landvalue']/join2010['shape_area']
join2010

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,geometry_x,the_geom,lon_coord,lat_coord,x_coord,y_coord,shape_area,shape_len,geometry_y,landvalue_sqft
0,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,POINT (-118.28456 34.05338),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28455814,34.05337712,6475471.82332,1841929.1484,13521.447266,470.334649481,POINT (-118.28456 34.05338),32.910752
1,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,POINT (-118.28444 34.06109),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28444197,34.06108702,6475514.95251,1844734.81795,8855.332031,415.074878377,POINT (-118.28444 34.06109),132.056031
2,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,POINT (-118.28568 34.06133),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28567752,34.061326,6475140.9776,1844822.84926,19059.246094,746.648966648,POINT (-118.28568 34.06133),131.390297
3,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,POINT (-118.28605 34.06050),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28604757,34.06050239,6475028.04528,1844523.44255,6830.428711,393.57457948,POINT (-118.28605 34.06050),29.280739
4,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,POINT (-118.28501 34.06129),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28500965,34.06129452,6475343.22777,1844810.81772,100532.499023,1343.89410917,POINT (-118.28501 34.06129),128.440058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,5402028009,90026-4022,34.07621231,-118.26869364,2010,300000,1678,2010,810 CORONADO TER LOS ANGELES CA 90026,Residential,...,POINT (-118.26869 34.07621),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26869434,34.07621263,6480299.29371,1850226.17628,5731.467773,329.140692477,POINT (-118.26869 34.07621),52.342613
2169,5424018007,90026-2322,34.08223393,-118.26787100,2010,388000,1066,2010,1326 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,POINT (-118.26787 34.08223),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.267871,34.08223393,6480554.46136,1852416.77032,4797.513672,319.884103451,POINT (-118.26787 34.08223),80.875225
2170,5424017011,90026-2215,34.08301413,-118.26851995,2010,639200,1968,2010,1342 N BENTON WAY LOS ANGELES CA 90026,Residential,...,POINT (-118.26852 34.08301),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26851995,34.08301413,6480358.71324,1852701.22073,5209.874023,340.536942721,POINT (-118.26852 34.08301),122.690107
2171,5424016027,90026-2323,34.08339106,-118.26781974,2010,503000,2052,2010,1407 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,POINT (-118.26782 34.08339),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26781974,34.08339106,6480571.10326,1852837.82668,4798.845703,319.987066318,POINT (-118.26782 34.08339),104.816873
2174,5424017010,90026-2215,34.08291563,-118.26857864,2010,553000,1369,2010,1338 N BENTON WAY LOS ANGELES CA 90026,Residential,...,POINT (-118.26858 34.08292),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26857864,34.08291563,6480340.84678,1852665.42276,5153.580078,337.691828565,POINT (-118.26858 34.08292),107.304047

In [21]:
censusjoin2010 = join2010.groupby('CT20').ain.count()
censusjoin2010

CT20
191301     6
195100    24
195400    27
195500     8
195600     6
          ..
221220    11
221602     6
224200     8
224310     3
224320     6
Name: ain, Length: 81, dtype: int64

In [22]:
df_census_n = pd.DataFrame(censusjoin2010)
df_census_n =df_census_n.rename(columns={'ain': 'n_parcel'})
df_census_n

        n_parcel
CT20
191301         6
195100        24
195400        27
195500         8
195600         6
...          ...
221220        11
221602         6
224200         8
224310         3
224320         6

[81 rows x 1 columns]

In [23]:
censuslvsfjoin2010 = join2010.groupby('CT20').landvalue_sqft.sum()
censuslvsfjoin2010

CT20
191301     487.864949
195100    2144.173925
195400    2310.469367
195500     908.825055
195600     556.425170
             ...
221220     657.914786
221602     211.975388
224200     561.730352
224310     210.831571
224320     383.565160
Name: landvalue_sqft, Length: 81, dtype: float64

In [24]:
df_lvsf = pd.DataFrame(censuslvsfjoin2010)
df_lvsf

        landvalue_sqft
CT20
191301      487.864949
195100     2144.173925
195400     2310.469367
195500      908.825055
195600      556.425170
...                ...
221220      657.914786
221602      211.975388
224200      561.730352
224310      210.831571
224320      383.565160

[81 rows x 1 columns]

In [25]:
df_lvsf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81 entries, 191301 to 224320
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   landvalue_sqft  81 non-null     float64
dtypes: float64(1)
memory usage: 3.3+ KB

In [26]:
df_census_n.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81 entries, 191301 to 224320
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   n_parcel  81 non-null     int64
dtypes: int64(1)
memory usage: 3.3+ KB

In [27]:
newjoin = df_lvsf.merge(df_census_n, how='left',on='CT20')
newjoin

        landvalue_sqft  n_parcel
CT20
191301      487.864949         6
195100     2144.173925        24
195400     2310.469367        27
195500      908.825055         8
195600      556.425170         6
...                ...       ...
221220      657.914786        11
221602      211.975388         6
224200      561.730352         8
224310      210.831571         3
224320      383.565160         6

[81 rows x 2 columns]

In [28]:
newjoin['avgprice_tract']=newjoin['landvalue_sqft']/newjoin['n_parcel']
newjoin

        landvalue_sqft  n_parcel  avgprice_tract
CT20
191301      487.864949         6       81.310825
195100     2144.173925        24       89.340580
195400     2310.469367        27       85.572940
195500      908.825055         8      113.603132
195600      556.425170         6       92.737528
...                ...       ...             ...
221220      657.914786        11       59.810435
221602      211.975388         6       35.329231
224200      561.730352         8       70.216294
224310      210.831571         3       70.277190
224320      383.565160         6       63.927527

[81 rows x 3 columns]

In [29]:
newjoin.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81 entries, 191301 to 224320
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   landvalue_sqft  81 non-null     float64
 1   n_parcel        81 non-null     int64
 2   avgprice_tract  81 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 2.5+ KB

In [30]:
#percent change with and without inflation

In [31]:
avgprice_tract_2020 = pd.read_csv('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/avgprice_tract_2020.csv')

In [32]:
avgprice_tract_2020.set_index('CT20')

        landvalue_sqft  n_parcel  avgprice_tract
CT20
188201      437.394742         4      109.348685
195100     4434.585512        26      170.560981
195400     4095.360087        25      163.814403
195500      989.321295         4      247.330324
195600      420.241248         2      210.120624
...                ...       ...             ...
224010     2316.198873         4      579.049718
224200      214.985409         2      107.492704
224310      446.980258         4      111.745065
224320      103.208982         1      103.208982
224410      116.962755         1      116.962755

[82 rows x 3 columns]

In [33]:
#rename columns
avgprice_tract_2020 = avgprice_tract_2020.rename(columns={'landvalue_sqft': 'landvalue_sqft_2020',
                                                         'n_parcel': 'n_parcel_2020',
                                                         'avgprice_tract':'avgprice_tract_2020'})

In [34]:
avgprice_tract_2020

      CT20  landvalue_sqft_2020  n_parcel_2020  avgprice_tract_2020
0   188201           437.394742              4           109.348685
1   195100          4434.585512             26           170.560981
2   195400          4095.360087             25           163.814403
3   195500           989.321295              4           247.330324
4   195600           420.241248              2           210.120624
..     ...                  ...            ...                  ...
77  224010          2316.198873              4           579.049718
78  224200           214.985409              2           107.492704
79  224310           446.980258              4           111.745065
80  224320           103.208982              1           103.208982
81  224410           116.962755              1           116.962755

[82 rows x 4 columns]

In [35]:
#calculate adjustments
newjoin

        landvalue_sqft  n_parcel  avgprice_tract
CT20
191301      487.864949         6       81.310825
195100     2144.173925        24       89.340580
195400     2310.469367        27       85.572940
195500      908.825055         8      113.603132
195600      556.425170         6       92.737528
...                ...       ...             ...
221220      657.914786        11       59.810435
221602      211.975388         6       35.329231
224200      561.730352         8       70.216294
224310      210.831571         3       70.277190
224320      383.565160         6       63.927527

[81 rows x 3 columns]

In [36]:
#rename columns
avgprice_tract_2010 = newjoin.rename(columns={'landvalue_sqft': 'landvalue_sqft_2010',
                                                         'n_parcel': 'n_parcel_2010',
                                                         'avgprice_tract':'avgprice_tract_2010'})

In [37]:
avgprice_tract_2010

        landvalue_sqft_2010  n_parcel_2010  avgprice_tract_2010
CT20
191301           487.864949              6            81.310825
195100          2144.173925             24            89.340580
195400          2310.469367             27            85.572940
195500           908.825055              8           113.603132
195600           556.425170              6            92.737528
...                     ...            ...                  ...
221220           657.914786             11            59.810435
221602           211.975388              6            35.329231
224200           561.730352              8            70.216294
224310           210.831571              3            70.277190
224320           383.565160              6            63.927527

[81 rows x 3 columns]

In [38]:
avgprice_tract_2010['2010avgprice_adjust_to_2020']=avgprice_tract_2010['avgprice_tract_2010']*1.19

In [39]:
avgprice_tract_2010

,landvalue_sqft_2010,n_parcel_2010,avgprice_tract_2010,2010avgprice_adjust_to_2020
CT20,,,,
191301,487.864949,6,81.310825,96.759882
195100,2144.173925,24,89.340580,106.315290
195400,2310.469367,27,85.572940,101.831798
195500,908.825055,8,113.603132,135.187727
195600,556.425170,6,92.737528,110.357659
...,...,...,...,...
221220,657.914786,11,59.810435,71.174418
221602,211.975388,6,35.329231,42.041785
224200,561.730352,8,70.216294,83.557390
224310,210.831571,3,70.277190,83.629856
224320,383.565160,6,63.927527,76.073757

In [40]:
avgprice_tract_2010.reset_index(inplace=True)
avgprice_tract_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CT20                         81 non-null     object
 1   landvalue_sqft_2010          81 non-null     float64
 2   n_parcel_2010                81 non-null     int64
 3   avgprice_tract_2010          81 non-null     float64
 4   2010avgprice_adjust_to_2020  81 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 3.3+ KB

In [41]:
avgprice_tract_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CT20                 82 non-null     int64
 1   landvalue_sqft_2020  82 non-null     float64
 2   n_parcel_2020        82 non-null     int64
 3   avgprice_tract_2020  82 non-null     float64
dtypes: float64(2), int64(2)
memory usage: 2.7 KB

In [42]:
#2010 to float
avgprice_tract_2010['CT20'] = avgprice_tract_2010.CT20.astype(float)
avgprice_tract_2010['n_parcel_2010'] = avgprice_tract_2010.n_parcel_2010.astype(float)

In [43]:
avgprice_tract_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CT20                         81 non-null     float64
 1   landvalue_sqft_2010          81 non-null     float64
 2   n_parcel_2010                81 non-null     float64
 3   avgprice_tract_2010          81 non-null     float64
 4   2010avgprice_adjust_to_2020  81 non-null     float64
dtypes: float64(5)
memory usage: 3.3 KB

In [44]:
#2020 to float
avgprice_tract_2020['CT20'] = avgprice_tract_2020.CT20.astype(float)
avgprice_tract_2020['n_parcel_2020'] = avgprice_tract_2020.n_parcel_2020.astype(float)

In [45]:
avgprice_tract_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CT20                 82 non-null     float64
 1   landvalue_sqft_2020  82 non-null     float64
 2   n_parcel_2020        82 non-null     float64
 3   avgprice_tract_2020  82 non-null     float64
dtypes: float64(4)
memory usage: 2.7 KB

In [46]:
#join
finaljoin=avgprice_tract_2010.merge(avgprice_tract_2020, how='left',on='CT20')

In [47]:
finaljoin=finaljoin.dropna()
finaljoin

,CT20,landvalue_sqft_2010,n_parcel_2010,avgprice_tract_2010,2010avgprice_adjust_to_2020,landvalue_sqft_2020,n_parcel_2020,avgprice_tract_2020
1,195100.0,2144.173925,24.0,89.340580,106.315290,4434.585512,26.0,170.560981
2,195400.0,2310.469367,27.0,85.572940,101.831798,4095.360087,25.0,163.814403
3,195500.0,908.825055,8.0,113.603132,135.187727,989.321295,4.0,247.330324
4,195600.0,556.425170,6.0,92.737528,110.357659,420.241248,2.0,210.120624
5,195710.0,523.470750,11.0,47.588250,56.630018,1025.013151,8.0,128.126644
...,...,...,...,...,...,...,...,...
76,221220.0,657.914786,11.0,59.810435,71.174418,1159.568842,9.0,128.840982
77,221602.0,211.975388,6.0,35.329231,42.041785,474.436340,4.0,118.609085
78,224200.0,561.730352,8.0,70.216294,83.557390,214.985409,2.0,107.492704
79,224310.0,210.831571,3.0,70.277190,83.629856,446.980258,4.0,111.745065
80,224320.0,383.565160,6.0,63.927527,76.073757,103.208982,1.0,103.208982

In [54]:
finaljoin['pct_change_wo_inflation'] = (finaljoin.loc[1:80,'avgprice_tract_2020'] - finaljoin.loc[1:80,'avgprice_tract_2010'])/finaljoin.loc[1:80,'avgprice_tract_2010']
#pct_change_wo_inflation
finaljoin['pct_change_w_inflation']=(finaljoin.loc[1:80,'avgprice_tract_2020'] - finaljoin.loc[1:80,'2010avgprice_adjust_to_2020'])/finaljoin.loc[1:80,'2010avgprice_adjust_to_2020']
#pct_change_w_inflation
finaljoin

,CT20,landvalue_sqft_2010,n_parcel_2010,avgprice_tract_2010,2010avgprice_adjust_to_2020,landvalue_sqft_2020,n_parcel_2020,avgprice_tract_2020,pct_change_wo_inflation,pct_change_w_inflation
1,195100.0,2144.173925,24.0,89.340580,106.315290,4434.585512,26.0,170.560981,0.909110,0.604294
2,195400.0,2310.469367,27.0,85.572940,101.831798,4095.360087,25.0,163.814403,0.914325,0.608676
3,195500.0,908.825055,8.0,113.603132,135.187727,989.321295,4.0,247.330324,1.177144,0.829532
4,195600.0,556.425170,6.0,92.737528,110.357659,420.241248,2.0,210.120624,1.265756,0.903997
5,195710.0,523.470750,11.0,47.588250,56.630018,1025.013151,8.0,128.126644,1.692401,1.262522
...,...,...,...,...,...,...,...,...,...,...
76,221220.0,657.914786,11.0,59.810435,71.174418,1159.568842,9.0,128.840982,1.154156,0.810215
77,221602.0,211.975388,6.0,35.329231,42.041785,474.436340,4.0,118.609085,2.357251,1.821219
78,224200.0,561.730352,8.0,70.216294,83.557390,214.985409,2.0,107.492704,0.530880,0.286454
79,224310.0,210.831571,3.0,70.277190,83.629856,446.980258,4.0,111.745065,0.590062,0.336186
80,224320.0,383.565160,6.0,63.927527,76.073757,103.208982,1.0,103.208982,0.614469,0.356696

In [58]:
gdf_2010['CT20']=gdf_2010.CT20.astype(float)

In [ ]:
gdf_2010.set_index('CT20',inplace=Tru)

In [65]:
finaljoin2=finaljoin.join(gdf_2010, rsuffix='CT20')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
finaljoin2

,CT20,landvalue_sqft_2010,n_parcel_2010,avgprice_tract_2010,2010avgprice_adjust_to_2020,landvalue_sqft_2020,n_parcel_2020,avgprice_tract_2020,pct_change_wo_inflation,pct_change_w_inflation,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,effectiveyearbuilt,parcelboundarydescription,roll_landbaseyear,location_1,OBJECTID_left,neighborhood,index_right,OBJECTID_right,CT20CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
1,195100.0,2144.173925,24.0,89.340580,106.315290,4434.585512,26.0,170.560981,0.909110,0.604294,5076004042,90006,34.05416636,-118.28739291,2010,58918,1050,2010,"940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 204 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
2,195400.0,2310.469367,27.0,85.572940,101.831798,4095.360087,25.0,163.814403,0.914325,0.608676,5076004067,90006,34.05416636,-118.28739291,2010,82485,1470,2010,"940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 502 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
3,195500.0,908.825055,8.0,113.603132,135.187727,989.321295,4.0,247.330324,1.177144,0.829532,5076004028,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 110 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
4,195600.0,556.425170,6.0,92.737528,110.357659,420.241248,2.0,210.120624,1.265756,0.903997,5076004030,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 102 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
5,195710.0,523.470750,11.0,47.588250,56.630018,1025.013151,8.0,128.126644,1.692401,1.262522,5076004052,90006,34.05416636,-118.28739291,2010,58918,1050,2010,"940 S ELDEN AVENUE, 304 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 304 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
6,195802.0,428.937974,6.0,71.489662,85.072698,927.566207,7.0,132.509458,0.853547,0.557603,5076005026,90006-5772,34.05288217,-118.28620793,2010,450444,18956,1996,980 MAGNOLIA AVE LOS ANGELES CA 90006,Residential,1963,CLARK AND BRYAN'S WESTMORELAND TRACT LOTS 67 A...,1996,"{'latitude': '34.05288217', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28621 34.05288)
7,195803.0,788.412192,11.0,71.673836,85.291864,2338.216702,11.0,212.565155,1.965729,1.492209,5076004048,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 310 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 310 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
8,195804.0,165.929682,3.0,55.309894,65.818774,1131.125461,9.0,125.680607,1.272299,0.909495,5076003027,90006-5607,34.05432240,-118.28868332,2010,150911,4013,1998,942 S WESTMORELAND AVE LOS ANGELES CA 90006,Residential,1916,CLARK AND BRYAN'S WESTMORELAND TRACT S 54 FT O...,1998,"{'latitude': '34.0543224', 'needs_recoding': F...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28868 34.05432)
9,195901.0,194.747009,4.0,48.686752,57.937235,4114.927664,14.0,293.923405,5.037030,4.073135,5076004026,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 108 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 108 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
10,195902.0,410.046320,7.0,58.578046,69.707874,2430.100741,12.0,202.508395,2.457070,1.905101,5076004032,90006,34.05416636,-118.28739291,2010,58918,1050,2010,"940 S ELDEN AVENUE, 104 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 104 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
11,195903.0,399.034434,8.0,49.879304,59.356372,2249.658463,15.0,149.977231,2.006803,1.526725,5076003005,90006-5705,34.05463690,-118.28813607,2010,71013,10096,1975,933 ELDEN AVE LOS ANGELES CA 90006,Residential,1923,HARPER'S MAGNOLIA PLACE LOT 12,1975,"{'latitude': '34.0546369', 'needs_recoding': F...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28814 34.05464)
12,208401.0,130.455523,3.0,43.485174,51.747357,1361.528225,7.0,194.504032,3.472882,2.758724,5076005004,90006-5798,34.05433407,-118.28575189,2010,211724,16230,2002,943 ARAPAHOE ST LOS ANGELES CA 90006,Residential,1989,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 39,2002,"{'latitude': '34.05433407', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28575 34.05433)
13,208402.0,225.258046,5.0,45.051609,53.611415,311.489261,1.0,311.489261,5.914054,4.810129,5076004001,90006-1856,34.05473729,-118.28739828,2010,361444,11858,2009,2720 SAN MARINO ST LOS ANGELES CA 90006,Residential,1951,HARPER'S MAGNOLIA PLACE LOTS 13 AND LOT 14,2009,"{'latitude': '34.05473729', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28740 34.05474)
14,208501.0,106.529185,3.0,35.509728,42.256577,644.060623,5.0,128.812125,2.627516,2.048333,5076004046,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 308 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 308 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
15,208502.0,467.059897,9.0,51.895544,61.755697,648.193465,5.0,129.638693,1.498070,1.099218,5076004065,90006,34.05416636,-118.28739291,2010,82485,1470,2010,"940 S ELDEN AVENUE, 504 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 504 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
16,208610.0,549.818412,13.0,42.293724,50.329532,1054.043332,10.0,105.404333,1.492198,1.094284,5076004002,90006-1852,34.05482843,-118.28692861,2010,180956,39370,1985,2700 SAN MARINO ST LOS ANGELES CA 90006,Residential,1928,HARPER'S MAGNOLIA PLACE LOT 15,1985,"{'latitude': '34.05482843', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28693 34.05483)
17,208620.0,379.638378,8.0,47.454797,56.471209,732.325391,8.0,91.540674,0.929008,0.621015,5076004036,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 208 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 208 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
18,208710.0,45.891908,14.0,3.277993,3.900812,127.095216,13.0,9.776555,1.982482,1.506287,5076004012,90006-5706,34.05280235,-118.28738030,2010,302944,4501,2003,984 ELDEN AVE LOS ANGELES CA 90006,Residential,1910,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 107,2003,"{'latitude': '34.05280235', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28738 34.05280)
19,208720.0,132.920925,2.0,66.460463,79.087951,316.995913,2.0,158.497956,1.384846,1.004072,5076005007,90006-5703,34.05381848,-118.28574693,2010,63229,4544,1975,957 ARAPAHOE ST LOS ANGELES CA 90006,Residential,1911,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 42,1975,"{'latitude': '34.05381848', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28575 34.05382)
20,208801.0,42.594688,1.0,42.594688,50.687678,1087.059190,2.0,543.529595,11.760502,9.723111,5076003004,90006-1862,34.05482203,-118.28808329,2010,741084,7992,2006,2760 SAN MARINO ST LOS ANGELES CA 90006,Residential,1951,HARPER'S MAGNOLIA PLACE E 132 FT OF LOT 11,2006,"{'latitude': '34.05482203', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28808 34.05482)
21,208802.0,367.870623,5.0,73.574125,87.553208,618.353408,3.0,206.117803,1.801499,1.354200,5076003012,90006-5734,34.05349354,-118.28812917,2010,212538,10320,1999,967 ELDEN AVE LOS ANGELES CA 90006,Residential,1962,CLARK AND BRYAN'S WESTMORELAND TRACT LOTS 124 ...,1999,"{'latitude': '34.05349354', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28813 34.05349)
22,208902.0,126.591464,2.0,63.295732,75.321921,429.367662,1.0,429.367662,5.783517,4.700434,5076003020,90006-5613,34.05304494,-118.28867589,2010,201630,20908,1998,978 S WESTMORELAND AVE LOS ANGELES CA 90006,Residential,1959,CLARK AND BRYAN'S WESTMORELAND TRACT LOTS 140 ...,1998,"{'latitude': '34.05304494', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28868 34.05304)
23,208903.0,73.307747,1.0,73.307747,87.236219,553.654872,2.0,276.827436,2.776237,2.173309,5076004044,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 206 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 206 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
24,208904.0,100.229295,2.0,50.114648,59.636431,132.981131,1.0,132.981131,1.653538,1.229864,5076004066,90006,34.05416636,-118.28739291,2010,82485,1470,2010,"940 S ELDEN AVENUE, 501 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 501 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
25,209300.0,187.142150,4.0,46.785538,55.674790,944.991284,5.0,188.998257,3.039673,2.394683,5076004060,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 402 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 402 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
26,209401.0,379.280810,3.0,126.426937,150.448054,1004.045779,4.0,251.011445,0.985427,0.668426,5076004008,90006-5774,34.05342252,-118.28691529,2010,1373360,44321,2002,955 MAGNOLIA AVE LOS ANGELES CA 90006,Residential,1960,CLARK AND BRYAN'S WESTMORELAND TRACT S 10 FT O...,2002,"{'latitude': '34.05342252', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28692 34.05342)
27,209402.0,199.992048,2.0,99.996024,118.995269,221.687591,4.0,55.421898,-0.445759,-0.534251,5076005027,90006-5708,34.05406869,-118.28598916,2010,243106,30294,1975,952 MAGNOLIA AVE LOS ANGELES CA 90006,Residential,1972,"CLARK AND BRYAN'S WESTMORELAND TRACT LOTS 40, ...",1975,"{'latitude': '34.05406869', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28599 34.05407)
29,209510.0,116.269802,2.0,58.134901,69.180532,499.440420,7.0,71.348631,0.227294,0.031340,5076003031,90006-5766,34.05375510,-118.28813120,2010,385544,40997,1988,961 ELDEN AVE LOS ANGELES CA 90006,Residential,1975,CLARK AND BRYAN'S WESTMORELAND TRACT LOTS 122 ...,1988,"{'latitude': '34.0537551', 'needs_recoding': F...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28813 34.05376)
30,209520.0,322.564090,7.0,46.080584,54.835895,230.194916,2.0,115.097458,1.497743,1.098944,5076003021,90006-5612,34.05331980,-118.28867762,2010,283244,12472,1985,970 S WESTMORELAND AVE LOS ANGELES CA 90006,Residential,1960,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 142 A...,1985,"{'latitude': '34.0533198', 'needs_recoding': F...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28868 34.05332)
31,209810.0,335.501073,6.0,55.916845,66.541046,302.924394,2.0,151.462197,1.708704,1.276222,5076004038,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 210 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 210 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
32,209820.0,331.090512,6.0,55.181752,65.666285,853.153235,6.0,142.192206,1.576798,1.165376,5076005011,90006-5703,34.05315861,-118.28574044,2010,204422,4542,1992,977 ARAPAHOE ST LOS ANGELES CA 90006,Residential,1904,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 46,1992,"{'latitude': '34.05315861', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28574 34.05316)
33,210010.0,312.989220,10.0,31.298922,37.245717,1591.111953,14.0,113.650854,2.631143,2.051380,5076003016,90006-2876,34.05262798,-118.28812057,2010,686678,6538,2002,2605 W OLYMPIC BLVD LOS ANGELES CA 90006,Commercial,1948,CLARK AND BRYAN'S WESTMORELAND TRACT EX OF ST ...,2002,"{'latitude': '34.05262798', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28812 34.05263)
34,211121.0,309.081774,5.0,61.816355,73.561462,256.176920,2.0,128.088460,1.072080,0.741244,5076004061,90006,34.05416636,-118.28739291,2010,58918,1050,2010,"940 S ELDEN AVENUE, 403 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 403 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
35,211122.0,173.467215,3.0,57.822405,68.808662,120.183421,1.0,120.183421,1.078492,0.746632,5076003032,90006-5765,34.05408536,-118.28813415,2010,385544,40997,1988,953 ELDEN AVE LOS ANGELES CA 90006,Residential,1975,CLARK AND BRYAN'S WESTMORELAND TRACT LOTS 120 ...,1988,"{'latitude': '34.05408536', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28813 34.05409)
36,211124.0,631.338681,17.0,37.137569,44.193708,836.516773,13.0,64.347444,0.732678,0.456032,5076004040,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 202 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 202 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
37,211201.0,362.496200,5.0,72.499240,86.274096,950.626264,5.0,190.125253,1.622445,1.203735,5076004063,90006,34.05416636,-118.28739291,2010,70140,1250,2010,"940 S ELDEN AVENUE, 405 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 405 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
38,211202.0,476.092366,6.0,79.348728,94.424986,788.417960,4.0,197.104490,1.484028,1.087419,5076004056,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 408 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 408 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
39,211310.0,268.196395,23.0,11.660713,13.876248,1836.608623,10.0,183.660862,14.750397,12.235628,5076004054,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 306 LOS ANGELES CA 90006",Residential,2009,TR=66665 LOT 1 CONDOUNIT 306 (AIRSPACE AND 1/4...,2008,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
40,211410.0,469.260544,7.0,67.037221,79.774292,258.907329,3.0,86.302443,0.287381,0.081833,5076004004,90006-5707,34.05449344,-118.28692519,2010,312000,2656,2006,939 MAGNOLIA AVE LOS ANGELES CA 90006,Residential,1908,LOT COM AT SE COR OF LOT 78 TH W ON S LINE OF ...,2006,"{'latitude': '34.05449344', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28693 34.05449)
41,211420.0,343.934492,7.0,49.133499,58.468864,293.628279,3.0,97.876093,0.992044,0.673987,5076004023,90006-6610,34.05305653,-118.28738284,2010,819260,17544,1990,976 ELDEN AVE LOS ANGELES CA 90006,Residential,1990,M B 5-71 LOTS 108 AND 109,1990,"{'latitude': '34.05305653', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28738 34.05306)
42,211500.0,609.676534,15.0,40.645102,48.367672,618.982935,7.0,88.426134,1.175567,0.828207,5076006013,90006-5704,34.05298254,-118.28502495,2010,1200000,0,2006,980 ARAPAHOE ST LOS ANGELES CA 90006,Commercial,0,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 28,2006,"{'latitude': '34.05298254', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28502 34.05298)
43,211703.0,389.182960,19.0,20.483314,24.375143,656.376417,19.0,34.546127,0.686550,0.417269,5076004018,90006-5778,34.05382920,-118.28738979,2010,863892,13924,2005,956 ELDEN AVE LOS ANGELES CA 90006,Residential,1963,CLARK AND BRYAN'S WESTMORELAND TRACT LOTS 112 ...,2005,"{'latitude': '34.0538292', 'needs_recoding': F...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05383)
44,211704.0,208.542623,25.0,8.341705,9.926629,565.802573,12.0,47.150214,4.652347,3.749872,5076003030,90006-2802,34.05262556,-118.28880498,2010,157916,2796,1979,2631 W OLYMPIC BLVD LOS ANGELES CA 90006,Commercial,1970,CLARK AND BRYAN'S WESTMORELAND TRACT W 88 FT E...,1979,"{'latitude': '34.05262556', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28880 34.05263)
45,211802.0,708.413535,35.0,20.240387,24.086060,744.426073,20.0,37.221304,0.838962,0.545346,5076005009,90006-5703,34.05348833,-118.28574372,2010,321000,2772,2008,967 ARAPAHOE ST LOS ANGELES CA 90006,Residential,1905,CLARK AND BRYAN'S WESTMORELAND TRACT LOT 44,2008,"{'latitude': '34.05348833', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28574 34.05349)
46,211803.0,102.031317,5.0,20.406263,24.283453,241.927685,5.0,48.385537,1.371112,0.992531,5076004010,90006-2986,34.05263237,-118.28690760,2010,420582,4228,1998,2569 W OLYMPIC BLVD LOS ANGELES CA 90006,Commercial,1962,CLARK AND BRYAN'S WESTMORELAND TRACT EX OF ST ...,1998,"{'latitude': '34.05263237', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28691 34.05263)
47,211804.0,176.388794,5.0,35.277759,41.980533,875.209091,5.0,175.041818,3.961818,3.169595,5076005002,90006-1843,34.05474611,-118.28579812,2010,156300,12114,1975,2650 SAN MARINO ST LOS ANGELES CA 90006,Residential,1949,HARPER'S MAGNOLIA PLACE LOT COM AT NE COR OF L...,1975,"{'latitude': '34.05474611', 'needs_recoding': ...",107.0,Westlake,684,685,213401.0,2134.01,2.110769e+06,6327.274225,POINT (-118.28580 34.05475)