In [2]:
import json
import pandas as pd
import geopandas as gpd

gdf_2010 = gpd.read_file('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/landvalue_2010_new.geojson')
#gdf_2010 = gdf_2010.rename(columns={'roll_totalvalue': 'roll_totalvalue_2010'})
#gdf_2010.set_index('ain',inplace=True)
gdf_2010

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,location_1,OBJECTID_left,neighborhood,index_right,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
0,5076004007,90006-5707,34.05402081,-118.28692121,2010,227767,0,2002,953 MAGNOLIA AVE LOS ANGELES CA 90006,Commercial,...,"{'latitude': '34.05402081', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28692 34.05402)
1,5076004042,90006,34.05416636,-118.28739291,2010,58918,1050,2010,"940 S ELDEN AVENUE, 204 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
2,5076004067,90006,34.05416636,-118.28739291,2010,82485,1470,2010,"940 S ELDEN AVENUE, 502 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
3,5076004028,90006,34.05416636,-118.28739291,2010,68457,1220,2010,"940 S ELDEN AVENUE, 110 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
4,5076004030,90006,34.05416636,-118.28739291,2010,80802,1440,2010,"940 S ELDEN AVENUE, 102 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05416636', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28739 34.05417)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41149,5443034007,90039-3714,34.09879045,-118.25012427,2010,47196,1344,1985,2010 SUNFLOWER AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09879045', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25012 34.09879)
41150,5443034040,90039-3708,34.09793157,-118.24867157,2010,44712,897,1980,1903 ROSEBUD AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09793157', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24867 34.09793)
41151,5443030020,90039-3715,34.09685223,-118.24962420,2010,50203,2818,2007,1909 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09685223', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24962 34.09685)
41152,5443035014,90039-3707,34.09866725,-118.24913765,2010,549257,12377,1987,2000 RIVERSIDE DR LOS ANGELES CA 90039,Commercial,...,"{'latitude': '34.09866725', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24914 34.09867)
41153,5443030015,90039-3715,34.09689235,-118.24994122,2010,140148,1115,1996,1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09689235', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24994 34.09689)

In [4]:
gdf_2010.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 41154 entries, 0 to 41153
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ain                        41154 non-null  object
 1   situszip                   41154 non-null  object
 2   center_lat                 41154 non-null  object
 3   center_lon                 41154 non-null  object
 4   rollyear                   41154 non-null  object
 5   roll_landvalue             41154 non-null  object
 6   sqftmain                   41154 non-null  object
 7   roll_impbaseyear           41154 non-null  object
 8   propertylocation           41154 non-null  object
 9   usecodedescchar1           41144 non-null  object
 10  effectiveyearbuilt         41154 non-null  object
 11  parcelboundarydescription  41154 non-null  object
 12  roll_landbaseyear          41154 non-null  object
 13  location_1                 41154 non-null  object
 14  OBJECTID_left              41154 non-null  float64
 15  neighborhood               41154 non-null  object
 16  index_right                41154 non-null  int64
 17  OBJECTID_right             41154 non-null  int64
 18  CT20                       41154 non-null  object
 19  LABEL                      41154 non-null  object
 20  ShapeSTArea                41154 non-null  float64
 21  ShapeSTLength              41154 non-null  float64
 22  geometry                   41154 non-null  geometry
dtypes: float64(3), geometry(1), int64(2), object(17)
memory usage: 7.2+ MB

In [5]:

gdf_2010.query('roll_landbaseyear == "2010"').roll_landbaseyear.count()

2186

In [6]:
gdf_2010_sold = gdf_2010[gdf_2010["roll_landbaseyear"] == '2010']
gdf_2010_sold

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,location_1,OBJECTID_left,neighborhood,index_right,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,"{'latitude': '34.05337712', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28456 34.05338)
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,"{'latitude': '34.06108702', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28444 34.06109)
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,"{'latitude': '34.061326', 'needs_recoding': Fa...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28568 34.06133)
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,"{'latitude': '34.06050239', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28605 34.06050)
191,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,"{'latitude': '34.06129452', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28501 34.06129)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40896,5443007007,90039-3946,34.09445414,-118.25052874,2010,392000,1208,2010,1964 LANDA ST LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09445414', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25053 34.09445)
41008,5443015013,90026-2053,34.09343035,-118.24598410,2010,396000,920,2010,2427 VALENTINE ST LOS ANGELES CA 90026,Residential,...,"{'latitude': '34.09343035', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24598 34.09343)
41086,5443027028,90039-3735,34.09648201,-118.24958644,2010,525000,888,2010,1908 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09648201', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24959 34.09648)
41107,5443028027,90039-3731,34.09575278,-118.25177910,2010,258600,1068,2010,1941 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09575278', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25178 34.09575)
41121,5443028035,90039-3739,34.09586083,-118.25144462,2010,365000,517,2010,2355 PERU ST LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09586083', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25144 34.09586)

In [7]:
min_number = min(gdf_2010_sold.ain)
print(min_number)
max_number = max(gdf_2010_sold.ain)
print(max_number)

5056001017
5518033027

In [8]:
#import parcel data
import requests
import json


url = 'https://data.lacounty.gov/resource/rjze-ndj2.json?$where=within_box(the_geom, 34.1164, -118.3217, 34.01333, -118.2675)&$limit=100000' # copied and pasted from the webpage
r = requests.get(url)
parcel = pd.DataFrame(json.loads(r.text))
parcel

#south:34.013339055368384, -118.23277272855023
#north: 34.11633386937314, -118.2674474941663
#eaast:34.01604254848126, -118.2217864006906
#west: 34.05453104173829, -118.32179797239648
#https://data.cityofchicago.org/resource/yama-9had.json?$where=within_polygon(the_geom, 'MULTIPOLYGON (((34.1037 -118.2484, 34.0054 -118.2455, 34.0545 -118.2062, 34.0633 -118.3351)))')
#within_polygon(location, 'MULTIPOLYGON (((34.10378510012116, -118.24846458486526, 34.00549184389096, -118.24552614565691, 34.05450056185422, -118.20622452124513, 34.06332521000708, -118.33514854151177)))')
#$where=ain>5056000000.0&$limit=2500000
#requestString = 'https://data.lacounty.gov/resource/rjze-ndj2.json&$limit=2100000'
#r = requests.get(requestString)
#d = json.loads(r.text)
#parcel = pd.DataFrame(d)
#parcel

,the_geom,lon_coord,ain,lat_coord,x_coord,y_coord,shape_area,shape_len
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32052234,5052003001,34.02944719,6464550.25589,1833253.40852,4118.85839844,268.710312492
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036613,5052003002,34.0294473,6464597.58649,1833253.29705,4118.71191406,268.700285953
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036544,5052003004,34.02927138,6464597.59358,1833189.27834,5822.9453125,366.020815496
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036271,5052003010,34.02859509,6464597.635,1832943.16,5821.99609375,366.000915114
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036179,5052003012,34.02836261,6464597.645,1832858.555,6561.81738281,376.420914855
...,...,...,...,...,...,...,...,...
52251,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29500987,5540014010,34.09448939,6472349.83528,1856899.75435,17708.1816406,537.983233013
52252,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.2942414,5540015005,34.094516,6472582.52329,1856908.75437,9905.31347656,485.910341354
52253,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29424216,5540016010,34.09423002,6472581.98691,1856804.68404,10059.3476563,487.292871966
52254,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29465601,5540023002,34.09311708,6472455.505,1856400.03,6749.98144531,370.00250984
52255,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.295756,5540026006,34.09132439,6472120.54739,1855748.61818,7204.76464844,388.192655311

In [9]:
parcel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52256 entries, 0 to 52255
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   the_geom    52256 non-null  object
 1   lon_coord   52256 non-null  object
 2   ain         52248 non-null  object
 3   lat_coord   52256 non-null  object
 4   x_coord     52256 non-null  object
 5   y_coord     52256 non-null  object
 6   shape_area  52256 non-null  object
 7   shape_len   52256 non-null  object
dtypes: object(8)
memory usage: 3.2+ MB

In [10]:
parcelgdf = gpd.GeoDataFrame(
    parcel, geometry=gpd.points_from_xy(parcel.lon_coord, parcel.lat_coord, 
                                          crs='EPSG:4326'))
parcelgdf

,the_geom,lon_coord,ain,lat_coord,x_coord,y_coord,shape_area,shape_len,geometry
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32052234,5052003001,34.02944719,6464550.25589,1833253.40852,4118.85839844,268.710312492,POINT (-118.32052 34.02945)
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036613,5052003002,34.0294473,6464597.58649,1833253.29705,4118.71191406,268.700285953,POINT (-118.32037 34.02945)
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036544,5052003004,34.02927138,6464597.59358,1833189.27834,5822.9453125,366.020815496,POINT (-118.32037 34.02927)
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036271,5052003010,34.02859509,6464597.635,1832943.16,5821.99609375,366.000915114,POINT (-118.32036 34.02860)
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036179,5052003012,34.02836261,6464597.645,1832858.555,6561.81738281,376.420914855,POINT (-118.32036 34.02836)
...,...,...,...,...,...,...,...,...,...
52251,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29500987,5540014010,34.09448939,6472349.83528,1856899.75435,17708.1816406,537.983233013,POINT (-118.29501 34.09449)
52252,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.2942414,5540015005,34.094516,6472582.52329,1856908.75437,9905.31347656,485.910341354,POINT (-118.29424 34.09452)
52253,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29424216,5540016010,34.09423002,6472581.98691,1856804.68404,10059.3476563,487.292871966,POINT (-118.29424 34.09423)
52254,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29465601,5540023002,34.09311708,6472455.505,1856400.03,6749.98144531,370.00250984,POINT (-118.29466 34.09312)
52255,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.295756,5540026006,34.09132439,6472120.54739,1855748.61818,7204.76464844,388.192655311,POINT (-118.29576 34.09132)

In [11]:
gdf_2010_sold = gdf_2010_sold.drop(columns=['index_right'])
gdf_2010_sold

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,roll_landbaseyear,location_1,OBJECTID_left,neighborhood,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,2010,"{'latitude': '34.05337712', 'needs_recoding': ...",107.0,Westlake,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28456 34.05338)
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,2010,"{'latitude': '34.06108702', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28444 34.06109)
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.061326', 'needs_recoding': Fa...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28568 34.06133)
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,2010,"{'latitude': '34.06050239', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28605 34.06050)
191,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.06129452', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28501 34.06129)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40896,5443007007,90039-3946,34.09445414,-118.25052874,2010,392000,1208,2010,1964 LANDA ST LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09445414', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25053 34.09445)
41008,5443015013,90026-2053,34.09343035,-118.24598410,2010,396000,920,2010,2427 VALENTINE ST LOS ANGELES CA 90026,Residential,...,2010,"{'latitude': '34.09343035', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24598 34.09343)
41086,5443027028,90039-3735,34.09648201,-118.24958644,2010,525000,888,2010,1908 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09648201', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24959 34.09648)
41107,5443028027,90039-3731,34.09575278,-118.25177910,2010,258600,1068,2010,1941 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09575278', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25178 34.09575)
41121,5443028035,90039-3739,34.09586083,-118.25144462,2010,365000,517,2010,2355 PERU ST LOS ANGELES CA 90039,Residential,...,2010,"{'latitude': '34.09586083', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25144 34.09586)

In [12]:
joinedgdf2010=gpd.sjoin(gdf_2010_sold.to_crs('EPSG:4326'),parcelgdf.to_crs('EPSG:4326'),how='left')
joinedgdf2010

,ain_left,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,geometry,index_right,the_geom,lon_coord,ain_right,lat_coord,x_coord,y_coord,shape_area,shape_len
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,POINT (-118.28456 34.05338),48427.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28455814,5076006006,34.05337712,6475471.82332,1841929.1484,13521.4472656,470.334649481
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,POINT (-118.28444 34.06109),50431.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28444197,5077013035,34.06108702,6475514.95251,1844734.81795,8855.33203125,415.074878377
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,POINT (-118.28568 34.06133),50517.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28567752,5077013036,34.061326,6475140.9776,1844822.84926,19059.2460938,746.648966648
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,POINT (-118.28605 34.06050),50476.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28604757,5077014048,34.06050239,6475028.04528,1844523.44255,6830.42871094,393.57457948
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,POINT (-118.28605 34.06050),50526.0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28604757,5077014053,34.06050239,6475028.04528,1844523.44255,6830.42871094,393.57457948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40896,5443007007,90039-3946,34.09445414,-118.25052874,2010,392000,1208,2010,1964 LANDA ST LOS ANGELES CA 90039,Residential,...,POINT (-118.25053 34.09445),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41008,5443015013,90026-2053,34.09343035,-118.24598410,2010,396000,920,2010,2427 VALENTINE ST LOS ANGELES CA 90026,Residential,...,POINT (-118.24598 34.09343),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41086,5443027028,90039-3735,34.09648201,-118.24958644,2010,525000,888,2010,1908 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,POINT (-118.24959 34.09648),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41107,5443028027,90039-3731,34.09575278,-118.25177910,2010,258600,1068,2010,1941 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,POINT (-118.25178 34.09575),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41121,5443028035,90039-3739,34.09586083,-118.25144462,2010,365000,517,2010,2355 PERU ST LOS ANGELES CA 90039,Residential,...,POINT (-118.25144 34.09586),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
gdf_2010_sold.head()

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,roll_landbaseyear,location_1,OBJECTID_left,neighborhood,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
110,5076006006,90006-1926,34.05337712,-118.28455814,2010,445001,5698,2010,963 S HOOVER ST LOS ANGELES CA 90006,Residential,...,2010,"{'latitude': '34.05337712', 'needs_recoding': ...",107.0,Westlake,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28456 34.05338)
162,5077013035,90005-3910,34.06108702,-118.28444197,2010,1169400,0,2010,667 S HOOVER ST LOS ANGELES CA 90005,Residential,...,2010,"{'latitude': '34.06108702', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28444 34.06109)
170,5077013036,90005-3913,34.06132600,-118.28567752,2010,2504200,3192,2010,2851 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.061326', 'needs_recoding': Fa...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28568 34.06133)
181,5077014054,90005-3977,34.06050239,-118.28604757,2010,200000,980,2010,"2864 SUNSET PL, 405 LOS ANGELES CA 90005",Residential,...,2010,"{'latitude': '34.06050239', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28605 34.06050)
191,5077013034,90005-3913,34.06129452,-118.28500965,2010,12912400,1278,2010,2809 SUNSET PL LOS ANGELES CA 90005,Commercial,...,2010,"{'latitude': '34.06129452', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28501 34.06129)

In [ ]:
join2010 = gdf_2010_sold.merge(parcelgdf, how='left',on='ain')
join2010 = join2010.dropna()
join2010

In [ ]:
join2010.query('neighborhood == "Westlake"').neighborhood.count()

In [ ]:
join2010.info()

In [ ]:
#join2010['roll_landvalue'].astype(float)
#join2010['shape_area'].astype(float)
join2010['shape_area'] = pd.to_numeric(join2010['shape_area'])
join2010['roll_landvalue'] = pd.to_numeric(join2010['roll_landvalue'])

In [ ]:
join2010.info()

In [ ]:
join2010['landvalue_sqft']=join2010['roll_landvalue']/join2010['shape_area']
join2010

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
join2010

In [ ]:

censusjoin2010 = join2010.groupby('CT20').ain.count()
censusjoin2010

In [ ]:
df_census_n = pd.DataFrame(censusjoin2010)
df_census_n =df_census_n.rename(columns={'ain': 'n_parcel'})
df_census_n

In [ ]:
censuslvsfjoin2010 = join2010.groupby('CT20').landvalue_sqft.sum()
censuslvsfjoin2010

In [ ]:
df_lvsf = pd.DataFrame(censuslvsfjoin2010)
df_lvsf

In [ ]:
df_lvsf.info()

In [ ]:
df_census_n.info()

In [ ]:
newjoin = df_lvsf.merge(df_census_n, how='left',on='CT20')
newjoin

In [ ]:
newjoin['avgprice_tract']=newjoin['landvalue_sqft']/newjoin['n_parcel']
newjoin

In [ ]:
#percent change with and without inflation

In [ ]:
avgprice_tract_2020 = pd.read_csv('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/avgprice_tract_2020.csv')

In [ ]:
avgprice_tract_2020.set_index('CT20')

In [ ]:
#rename columns
avgprice_tract_2020 = avgprice_tract_2020.rename(columns={'landvalue_sqft': 'landvalue_sqft_2020',
                                                         'n_parcel': 'n_parcel_2020',
                                                         'avgprice_tract':'avgprice_tract_2020'})
avgprice_tract_2020

In [ ]:
#rename columns
avgprice_tract_2010 = newjoin.rename(columns={'landvalue_sqft': 'landvalue_sqft_2010',
                                                         'n_parcel': 'n_parcel_2010',
                                                         'avgprice_tract':'avgprice_tract_2010'})
avgprice_tract_2010

In [ ]:
avgprice_tract_2010['2010avgprice_adjust_to_2020']=avgprice_tract_2010['avgprice_tract_2010']*1.19
avgprice_tract_2010

In [ ]:
avgprice_tract_2010.reset_index(inplace=True)
avgprice_tract_2010.info()

In [ ]:
avgprice_tract_2020.info()

In [ ]:
#2010 to float
avgprice_tract_2010['CT20'] = avgprice_tract_2010.CT20.astype(int)
avgprice_tract_2010['n_parcel_2010'] = avgprice_tract_2010.n_parcel_2010.astype(float)
avgprice_tract_2010.info()

In [ ]:
#2020 to float
avgprice_tract_2020['CT20'] = avgprice_tract_2020.CT20.astype(int)
avgprice_tract_2020['n_parcel_2020'] = avgprice_tract_2020.n_parcel_2020.astype(float)
avgprice_tract_2020.info()

In [ ]:
#join
finaljoin=avgprice_tract_2010.merge(avgprice_tract_2020, how='left',on='CT20')
finaljoin=finaljoin.dropna()
finaljoin

In [ ]:
finaljoin['pct_change_wo_inflation'] = (finaljoin.loc[1:80,'avgprice_tract_2020'] - finaljoin.loc[1:80,'avgprice_tract_2010'])/finaljoin.loc[1:80,'avgprice_tract_2010']
#pct_change_wo_inflation
finaljoin['pct_change_w_inflation']=(finaljoin.loc[1:80,'avgprice_tract_2020'] - finaljoin.loc[1:80,'2010avgprice_adjust_to_2020'])/finaljoin.loc[1:80,'2010avgprice_adjust_to_2020']
#pct_change_w_inflation
finaljoin

In [ ]:
#finaljoin['CT20']=finaljoin.CT20.astype(int)
#gdf_2010['CT20']=gdf_2010.CT20.astype(int)
#finaljoin.info()

In [ ]:
#gdf_2010.set_index('CT20',inplace=True)
#finaljoin.set_index('CT20',inplace=True)

In [ ]:
#finaljoin2=finaljoin.join(gdf_2010.drop(columns='CT20'))
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
#finaljoin2

In [ ]:
census = gpd.read_file('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/Data/Census_Tracts_2020.geojson')
census.head()

In [ ]:
gdf_2010.info()

In [ ]:
census.info()

In [ ]:
census['CT20']=census.CT20.astype(int)

In [ ]:
#use this for mapping
census_finaljoin=finaljoin.merge(census, on='CT20',how='left')
census_finaljoin

In [ ]:
#neighborhood boundary
nb= gpd.read_file('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/Data/LA_Times_Neighborhood_Boundaries (1)-Copy1.geojson')
#nb.name
wl=nb[nb.name=='Westlake']
kt=nb[nb.name=='Koreatown']
pu=nb[nb.name=='Pico-Union']
sl=nb[nb.name=='Silver Lake']
dt=nb[nb.name=='Downtown']
ep=nb[nb.name=='Echo Park']
join1 = pd.concat([wl, kt], axis=0).reset_index(drop=True)
join2 = pd.concat([join1, pu], axis=0).reset_index(drop=True)
join3 = pd.concat([join2, sl], axis=0).reset_index(drop=True)
join4 = pd.concat([join3, dt], axis=0).reset_index(drop=True)
nb = pd.concat([join4, ep], axis=0).reset_index(drop=True)
nb

In [ ]:
census_finaljoin.CT20=census_finaljoin.CT20.astype(object)

In [ ]:
#merge census final join with nb
#no good
mergetest=census_finaljoin.merge(gdf_2010, on='CT20')
mergetest

In [ ]:
import geopandas as gpd
gdf=gpd.GeoDataFrame(census_finaljoin,geometry='geometry')

In [ ]:
gdf_2010.info()

In [ ]:
gdf_2010= gdf_2010.drop(columns=['index_right'])
gdf_2010

In [ ]:
mergetest2=gpd.sjoin(gdf.to_crs('EPSG:4326'),gdf_2010.to_crs('EPSG:4326'),how='left')
mergetest2

In [ ]:
census_finaljoin.info()

In [ ]:
gdf.columns

In [ ]:
#change to geodataframe
import geopandas as gpd
gdf=gpd.GeoDataFrame(census_finaljoin,geometry='geometry')

In [ ]:
#map
import contextily as ctx
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,10))
gdf.to_crs('EPSG:3857').plot('pct_change_wo_inflation',
                             markersize=0.001, 
                             ax=ax, legend=True)
#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])
ax.set_title('land value pct_change_without_inflation', fontsize=20 )

In [ ]:
gdf.pct_change_w_inflation.max()

In [ ]:
gdf.pct_change_w_inflation.min()

In [ ]:
gdf.pct_change_w_inflation.median()

In [ ]:
#map
#natural break
import contextily as ctx
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,10))
#gdf.to_crs('EPSG:3857').plot('pct_change_w_inflation',
                             #markersize=0.001, 
                             #ax=ax, legend=True)
        
gdf.to_crs('EPSG:3857').plot(figsize=(12,12),
            column='pct_change_w_inflation', 
            cmap='RdYlGn_r', 
            scheme='NaturalBreaks', # to use custom breaks
            #classification_kwds={'bins':[-1,50,]}, # define the breaks here
            edgecolor='white', 
            linewidth=0.1, 
            legend=True,
            ax=ax
           )

#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])
ax.set_title('land value pct_change_with_inflation', fontsize=20 )

In [ ]:
#equal interval
import contextily as ctx
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,10))
#gdf.to_crs('EPSG:3857').plot('pct_change_w_inflation',
                             #markersize=0.001, 
                             #ax=ax, legend=True)
        
gdf.to_crs('EPSG:3857').plot(figsize=(12,12),
            column='pct_change_w_inflation', 
            cmap='RdYlGn_r', 
            scheme='equal_interval', # to use custom breaks
            #classification_kwds={'bins':[-1,50,]}, # define the breaks here
            edgecolor='white', 
            linewidth=0.1, 
            legend=True,
            ax=ax
           )

#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])
ax.set_title('land value pct_change_with_inflation', fontsize=20 )

In [ ]:
#quantiles
import contextily as ctx
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,10))
#gdf.to_crs('EPSG:3857').plot('pct_change_w_inflation',
                             #markersize=0.001, 
                             #ax=ax, legend=True)
        
gdf.to_crs('EPSG:3857').plot(figsize=(12,12),
            column='pct_change_w_inflation', 
            cmap='RdYlGn_r', 
            scheme='quantiles', # to use custom breaks
            #classification_kwds={'bins':[-1,50,]}, # define the breaks here
            edgecolor='white', 
            linewidth=0.1, 
            legend=True,
            ax=ax
           )

#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])
ax.set_title('land value pct_change_with_inflation', fontsize=20 )

In [ ]:
#map
#natural break
import contextily as ctx
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,10))
#gdf.to_crs('EPSG:3857').plot('pct_change_w_inflation',
                             #markersize=0.001, 
                             #ax=ax, legend=True)
        
gdf.to_crs('EPSG:3857').plot(figsize=(12,12),
            column='pct_change_w_inflation', 
            cmap='RdYlGn_r', 
            scheme='user_defined', # to use custom breaks
            classification_kwds={'bins':[-1,-0.5,0,0.5,1,2,5,10,20,30,40,50]}, # define the breaks here
            edgecolor='white', 
            linewidth=0.1, 
            legend=True,
            ax=ax
           )

#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])
ax.set_title('land value pct_change_with_inflation', fontsize=20 )

In [ ]:
from matplotlib import pyplot as plt
import numpy as np

xa = np.linspace(0, 5, 20)

fig, ax = plt.subplots(figsize=(10,10))
#gdf.to_crs('EPSG:3857').plot('pct_change_w_inflation',
                             #markersize=0.001, 
                             #ax=ax, legend=True)
        
gdf.to_crs('EPSG:3857').plot(figsize=(12,12),
            column='pct_change_w_inflation', 
            cmap='RdYlGn_r', 
            scheme='NaturalBreaks', # to use custom breaks
            #classification_kwds={'bins':[-1,50,]}, # define the breaks here
            edgecolor='white', 
            linewidth=0.1, 
            legend=True,
            ax=ax
           )
nb=xa**2
nb.to_crs('EPSG:3857').plot('name',
                           color='lightcoral', linewidth=4, linestyle=':', 
                            ax=ax)

#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])
ax.set_title('land value pct_change_with_inflation', fontsize=20 )

In [ ]:
m = folium.Map(zoom_start=10,
              location=[34.052235, -118.243683])
folium.Choropleth(
    geo_data='/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/landvalue_pctchange.geojson',
    name='pct_change_w_inflation',
    data=gdf,
    popup=gdf.pct_change_w_inflation,
    columns=['CT20', 'pct_change_w_inflation'],
    fill_color='YlGn',
    key_on='feature.properties.CT20',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='pct_change_w_inflation'
).add_to(m)

m

In [ ]:
for index, row in nb.iterrows():
    # add folium marker code
    folium.Marker([row.LAT, row.LONG], popup=row.name, tooltip=row.STATION).add_to(m)
m

In [ ]:
folium.Choropleth(
    geo_data=gdf,
    name='pct_change_w_inflation',
    data=gdf,
    popup=gdf.pct_change_w_inflation,
    columns=['CT20', 'pct_change_w_inflation'],
    fill_color='YlGn',
    key_on='feature.properties.CT20',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='pct_change_w_inflation'
).add_to(m)

# show the map
m

In [ ]:
m =folium.Map(location=[34.051850, -118.243322], tiles=None) #Center map on LA County

#Adding basemap
folium.raster_layers.TileLayer(
    location=[34.051850, -118.243322],
    tiles='https://api.mapbox.com/styles/v1/jinglan9803/ckvb8q3fa8ocm15s2h2chib9k/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiamluZ2xhbjk4MDMiLCJhIjoiY2wzd2w2eGRhMGhkZjNpcnF5ZWtocHZrciJ9.iJrdUieRYeaerd-cqJLNzw',
    attr='Mapbox',
    API_key='pk.eyJ1IjoiamluZ2xhbjk4MDMiLCJhIjoiY2wzd2wyeDZyMTR2ZDNpcDQ1a3RvN2FnaCJ9.HaceX4lYSqLYsUpUQE9X_Q',
    name='Monochrome',
    zoom_start=9  # Limited levels of zoom for free Mapbox tiles.
).add_to(m)

#Chloropleth
folium.Choropleth(
    geo_data=gdf,
    name='pct_change_w_inflation',
    data=gdf,
    popup=gdf.pct_change_w_inflation,
    columns=['CT20', 'pct_change_w_inflation'],
    fill_color='YlGn',
    key_on='feature.properties.CT20',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='pct_change_w_inflation'
).add_to(m)

#second layer to add to map
f2=folium.FeatureGroup(name='nb').add_to(m)



#m.save('schoolsandstores.html')

m

In [ ]:
import pandas as pd
us_cities = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/us-cities-top-1k.csv")

import plotly.express as px

fig = px.scatter_mapbox(us_cities, lat="lat", lon="lon", hover_name="City", hover_data=["State", "Population"],
                        color_discrete_sequence=["fuchsia"], zoom=3, height=300)
fig.update_layout(mapbox_style="open-street-map")
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [ ]:
#markers
#for index, row in gdf_trimmed.iterrows():
    #folium.Circle([row.latitude, row.longitude], popup=row.Name, tooltip=row.Name, color="purple").add_to(f2)

#f3=folium.FeatureGroup(name='Trader Joes Stores').add_to(m)

for index, row in tj_trimmed.iterrows():
    folium.Circle([row.Latitude, row.Longitude], popup=row.Store_Chain, tooltip=row.Store_Chain,color="blue").add_to(f3)

f4=folium.FeatureGroup(name='Whole Foods Stores').add_to(m)

for index, row in wf_trimmed.iterrows():
    folium.Circle([row.Latitude, row.Longitude], popup=row.Store_Chain, tooltip=row.Store_Chain,color="green").add_to(f4)

f5=folium.FeatureGroup(name='Vons Stores').add_to(m)

for index, row in vns_trimmed.iterrows():
    folium.Circle([row.Latitude, row.Longitude], popup=row.Store_Chain, tooltip=row.Store_Chain,color="crimson").add_to(f5)

    
folium.LayerControl(position='topright', collapsed=True, autoZIndex=True).add_to(m)

In [ ]:

fig, ax = plt.subplots(figsize=(10,10))
gdf_2010.to_crs('EPSG:3857').plot('neighborhood',
                             #markersize=1, 
                             #ax=ax, legend=True)
#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])

nb.to_crs('EPSG:3857').plot('name',
                           markersize=1, 
                            ax=ax, legend=True)

ax.set_title('Neighborhood by Ain', fontsize=20 )

In [ ]:
#map
import contextily as ctx
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(20,20))
nb.to_crs('EPSG:3857').plot('name',
                             markersize=0.001, 
                             ax=ax, legend=True)
#ax.set_ylim([3.98e6,4.14e6])
ctx.add_basemap(ax=ax)    
#ax.set_xticks([])
#ax.set_yticks([])
ax.set_title('nb', fontsize=40 )

In [ ]:
gdf_2010_sjoin.to_file('landvalue_2010_new.geojson', driver='GeoJSON')